### ISSUE TITLE
How to enable both DNS and TLS ALPN challenges?

### ISSUE THREAD

**Issue by ImedAdel** [caddyserver/certmagic#100]
## What is your question?

I would like to enable both DNS (for wildcard subdomains) and TLS ALPN (for on-demand domain names). The documentation mentions adding _another_ ACMEManager but I couldn't understand how the pieces are supposed to fit together.

## What have you already tried?

This example uses Gin for routing and Namecheap as a DNS provider.
```go
certmagic.Default.OnDemand = new(certmagic.OnDemandConfig)
certmagic.DefaultACME.CA = certmagic.LetsEncryptStagingCA
certmagic.DefaultACME.Email = "my@gmail.com"
certmagic.DefaultACME.Agreed = true
provider, err := namecheap.NewDNSProvider()
if err != nil {
	log.Fatal(err)
}
certmagic.DefaultACME.DNSProvider = provider

magic := certmagic.NewDefault()
magic.ManageSync([]string{"example.com", "*.example.com"})
ln, err := tls.Listen("tcp", ":443", magic.TLSConfig())
if err != nil {
	log.Fatal(err)
}
r := gin.Default()
r.GET("/*filepath", serve)
s := &http.Server{
	ReadHeaderTimeout: 20 * time.Second,
	ReadTimeout:       10 * time.Second,
	WriteTimeout:      30 * time.Second,
	Handler:           r,
}
err = s.Serve(ln)
if err != nil {
	log.Fatal(err)

}
```

**Comment by ImedAdel** [comment]
I don't know why I haven't realized this yesterday but the solution is to either run two servers with the same storage or, using Gin, to run two [services](https://github.com/gin-gonic/gin#run-multiple-service-using-gin).

**Comment by mholt** [comment]
>  the solution is to either run two servers with the same storage or, using Gin, to run two services.

While you can certainly do that, that doesn't sound quite right, or like the easiest solution.

First, I want to understand why you need to do this. Usually the DNS challenge is used only in situations where the TLS-ALPN or HTTP challenges won't succeed. Why use the TLS-ALPN challenge at all?

**Comment by ImedAdel** [comment]
Yup. After a bit of refactoring, I realized that it doesn't work that way. My app users can have a free subdomain (thus the need for a wildcard certificate and the DNS challenge) and they can also attach their own custom domain (thus the need for TLS-ALPN or HTTP challenges). 

Caddy can handle this, but I have to keep adding every new custom domain through the API.<sup>1</sup> I do it automatically but it doesn't work if I want to autoscale the Caddy server (like on ECS or k8s) since I'd need to copy the config.

-----
1. I guess I can use Caddy both for on-demand TLS and the wildcard subdomain, and proxy everything to my server to handle serving the apps? Is this possible/recommended? 🤔

**Comment by francislavoie** [comment]
Yeah, that's a pretty typical usecase for Caddy.

**Comment by mholt** [comment]
You can do it with CertMagic too. For the domains that you control (including your wildcard), use a Config with the DNS challenge enabled. For all the on-demand certificates, simply use a different Config that doesn't enable it.

**Comment by ImedAdel** [comment]
Thank you, everyone! Although Caddy seems to be a more straightforward solution, I still have to debug the Redis storage module and the deprecated Lego module 😄 So, @mholt, would it be possible to give me an example for using two configs at the same time while listening on the same port? Because I can't figure out how to do it.

**Comment by mholt** [comment]
It's not so much using "two configs at the same time" -- which _isn't_ a thing, you must choose one per certificate per operation -- as it is specifying a `GetConfigForCert` callback that returns the right config for the given certificate: https://pkg.go.dev/github.com/caddyserver/certmagic#CacheOptions

That's for renewals and stuff. To initially obtain certificates, use the right config with `ManageSync()` or `ManageAsync()`: https://pkg.go.dev/github.com/caddyserver/certmagic#Config.ManageSync
