### ISSUE TITLE
Simplest way to disable a challenge type?

### ISSUE THREAD

**Issue by anderspitman** [caddyserver/certmagic#102]
I want to disable the HTTP challenge, but I'm getting bogged down in the boilerplate from the README. From reading the docs, creating a custom cache sounds particularly dangerous. Is there a simpler way?

**Comment by anderspitman** [comment]
Would setting `certmagic.DefaultACME.DisableHTTPChallenge = true` before running my code work?

**Comment by mholt** [comment]
Yeah, that's probably what you want.

The godoc is pretty straightforward here and would be helpful: https://pkg.go.dev/github.com/caddyserver/certmagic#ACMEManager.DisableHTTPChallenge

**Comment by anderspitman** [comment]
Thanks @mholt! I had been reading the godocs, but was still confused. They're making a lot more sense now. I think I was just tired.
