### ISSUE TITLE
[Gandi] Wrong DNS TXT record causes unable to get certificate

### ISSUE THREAD

**Issue by SkYNewZ** [caddyserver/certmagic#105]
## What version of the package are you using?

`CADDY_VERSION=v2.2.0 xcaddy build --with github.com/caddy-dns/gandi`

## What are you trying to do?

Use Caddy as usual, with HTTPS solves with dns-01 challenge

## What steps did you take?

```
cloud.skynewz.dev, *.cloud.skynewz.dev
tls contact@skynewz.dev {
	dns gandi {env.GANDI_API_TOKEN}
}
respond "Hello, world!"
```

## What did you expect to happen, and what actually happened instead?

Caddy can get my certificate and alright !
Instead, something creates a TXT record that Caddy cannot solve and Caddy never start, lopping on resolving the challenge

## Please link to any related issues, pull requests, and/or discussion

https://github.com/caddyserver/caddy/issues/3787

**Comment by SkYNewZ** [comment]
@mholt I can see here that you create a "good" TXT record... I don't find how I end up with this `_acme-challenge.cloud.skynewz.dev`

**Comment by SkYNewZ** [comment]
Always exist with the last update of Caddy
![image](https://user-images.githubusercontent.com/26750012/95901281-645b7100-0d93-11eb-8a23-fc2ff5f27b3e.png)

**Comment by obynio** [comment]
Please avoid relying on the Gandi UI. Can you rather provide us with the content of the DNS file with the challenge in it for the domain `skynewz.dev` and `lemairepro.fr`

**Comment by obynio** [comment]
And the TXT record is actually created by the Gandi plugin which relies on the libdns Gandi plugin for that based on the data provided by certmagic.

https://github.com/obynio/certbot-plugin-gandi
https://github.com/libdns/gandi

**Comment by obynio** [comment]
Okay I managed to reproduce the issue on Go 1.15.1 with the Gandi plugin compiled with xcaddy with the following caddyfile

```
pad.leon.re {
	tls {
		dns gandi {env.GANDI_API_TOKEN}
	}
	respond "Hello, world!"
}
```

 The record is correctly created in the zone and seems to comply with the RFC

```
_acme-challenge.pad.leon.re 10800 IN TXT "REDACTED"
```
It appears certmagic is timeouting when trying to get the record.

```
Oct 14 17:23:01 bifrost caddy[307390]: {"level":"error","ts":1602688981.3301451,"logger":"tls.obtain","msg":"will retry","error":"[pad.leon.re] Obtain: [pad.leon.re] solving challenges: waiting for solver *certmagic.DNS01Solver to be ready: timed out waiting for record to fully propagate; verify DNS provider configuration is correct - last error: <nil>  (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/16115184/166956908) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)","attempt":2,"retrying_in":120,"elapsed":307.026609925,"max_duration":2592000}
```
I will try to investigate further when I get some time.

**Comment by obynio** [comment]
Error comes from here, we can trace the call stack https://github.com/caddyserver/certmagic/blob/master/solvers.go#L347

**Comment by obynio** [comment]
Mhhh I just realized that if the issue comes from certmagic Gandi should not be the only DNS provider affected by the incident 🤔

**Comment by obynio** [comment]
Certmagic checks by default in the `/etc/resolv.conf` and is using the following list to check for DNS propagation.

https://github.com/caddyserver/certmagic/blob/master/dnsutil.go#L325

**Comment by obynio** [comment]
Yes, if you could give me the content of the zone file of your DigitalOcean domain that would be very helpful.

**Comment by SkYNewZ** [comment]
> Certmagic checks by default in the `/etc/resolv.conf` and is using the following list to check for DNS propagation.
> 
> https://github.com/caddyserver/certmagic/blob/master/dnsutil.go#L325

Yes I saw that too, but I don't think it affects the process because Caddy v2.1.0 also use a predefined list or `resolve.conf` and its works (for me at least)

**Comment by SkYNewZ** [comment]
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/26750012/96019697-2de22c80-0e4d-11eb-8879-e9cada899139.png">

**Comment by obynio** [comment]
I reached the internal rate limiter of caddy, but I think I have lead for the cause of the issue. I need to confirm it first.

**Comment by SkYNewZ** [comment]
Do you need some help ?

**Comment by SkYNewZ** [comment]
> I reached the internal rate limiter of caddy, but I think I have lead for the cause of the issue. I need to confirm it first.

If you need my domain `skynewz.tk` for testing, I can give you access

**Comment by obynio** [comment]
No it is fine, don't worry 🙂  I tink it may be a typo in the DNS record submitted to Gandi. I need to test a bit to know to which extend I can bend the Gandi API for my needs.

**Comment by obynio** [comment]
But still it is strange to have the issue on Go 1.15.1 and not on Go 1.14 🤔

**Comment by SkYNewZ** [comment]
Hum I never tried Caddy v2.2.0 (or 2.2.1) with Go 1.14

**Comment by obynio** [comment]
Yeah I mean I'm using it on my personal infrastructure and never had an issue with my domains

**Comment by SkYNewZ** [comment]
This does not work for me on latest version and Go 1.14 🤔
https://asciinema.org/a/365375

**Comment by obynio** [comment]
Okay I found the issue. It seems there is a breaking change in the record provided by Caddy to the Gandi plugin between Caddy v2.1.1 and Caddy v2.2.0. Because of some strange regexp in the Gandi API, I have to trim the record name provided by Caddy from `_acme-challenge.hello.leon.re` to `_acme-challenge.hello` and then submit it to the gandi API.

https://github.com/libdns/gandi/blob/master/client.go#L20

Until Caddy v2.1.1 the `record.Name` provided by Caddy was `_acme-challenge.hello.leon.re.`
Therefore the above code would trim `_acme-challenge.hello.leon.re.` to  `_acme-challenge.hello` as expected.

But since Caddy v2.2.0 the `record.Name` provided by Caddy is `_acme-challenge.hello.leon.re` without the `.` at the end, notice the subtle difference. Thus the `TrimSuffix` does not trim anymore.

**Comment by SkYNewZ** [comment]
Well done ! Indeed, it is a very subtle difference…
So you plan to remove this line do fix the issue ?

**Comment by obynio** [comment]
Unfortunately we need a fix that is retro-compatible with both version. I'm working on it.

**Comment by SkYNewZ** [comment]
Yes I forget this details… Maybe the issue come from the format of `record.Name` ? With and without the ending dot ?

**Comment by obynio** [comment]
I've released a fix, you can try again now.

https://github.com/caddy-dns/gandi/releases/tag/v1.0.1
https://github.com/libdns/gandi/releases/tag/v1.0.2

**Comment by francislavoie** [comment]
Well done @obynio :clap: 

I think the digitalocean plugin also has a similar issue https://github.com/libdns/digitalocean/pull/3

**Comment by SkYNewZ** [comment]
```
~/Sources/caddyv2/test using ☁️  default/iwc-apipy-ss-int-dtep 
➜ ./caddy version 
v2.2.1 h1:Q62GWHMtztnvyRU+KPOpw6fNfeCD3SkwH7SfT1Tgt2c=

~/Sources/caddyv2/test using ☁️  default/iwc-apipy-ss-int-dtep 
➜ GANDI=XX ./caddy run
2020/10/14 19:29:21.407	INFO	using adjacent Caddyfile
2020/10/14 19:29:21.408	INFO	admin	admin endpoint started	{"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["localhost:2019", "[::1]:2019", "127.0.0.1:2019"]}
2020/10/14 19:29:21.408	INFO	tls.cache.maintenance	started background certificate maintenance	{"cache": "0xc0003811f0"}
2020/10/14 19:29:21.408	INFO	http	server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS	{"server_name": "srv0", "https_port": 443}
2020/10/14 19:29:21.408	INFO	http	enabling automatic HTTP->HTTPS redirects	{"server_name": "srv0"}
2020/10/14 19:29:21.409	INFO	http	enabling automatic TLS certificate management	{"domains": ["foo.lemairepro.fr"]}
2020/10/14 19:29:21.409	INFO	autosaved config	{"file": "/Users/quentin/Library/Application Support/Caddy/autosave.json"}
2020/10/14 19:29:21.409	INFO	serving initial configuration
2020/10/14 19:29:21.409	INFO	tls.obtain	acquiring lock	{"identifier": "foo.lemairepro.fr"}
2020/10/14 19:29:21.410	INFO	tls.obtain	lock acquired	{"identifier": "foo.lemairepro.fr"}
2020/10/14 19:29:21.410	INFO	tls	cleaned up storage units
2020/10/14 19:29:21.418	INFO	tls.issuance.acme	waiting on internal rate limiter	{"identifiers": ["foo.lemairepro.fr"]}
2020/10/14 19:29:21.418	INFO	tls.issuance.acme	done waiting on internal rate limiter	{"identifiers": ["foo.lemairepro.fr"]}
2020/10/14 19:29:22.647	INFO	tls.issuance.acme.acme_client	trying to solve challenge	{"identifier": "foo.lemairepro.fr", "challenge_type": "dns-01", "ca": "https://acme-staging-v02.api.letsencrypt.org/directory"}
2020/10/14 19:29:27.531	INFO	tls.issuance.acme.acme_client	validations succeeded; finalizing order	{"order": "https://acme-staging-v02.api.letsencrypt.org/acme/order/16049959/167051539"}
2020/10/14 19:29:28.720	INFO	tls.issuance.acme.acme_client	successfully downloaded available certificate chains	{"count": 2, "first_url": "https://acme-staging-v02.api.letsencrypt.org/acme/cert/fa89b5b098c58e3846fbd931e35bbbce92a1"}
2020/10/14 19:29:28.722	INFO	tls.obtain	certificate obtained successfully	{"identifier": "foo.lemairepro.fr"}
2020/10/14 19:29:28.722	INFO	tls.obtain	releasing lock	{"identifier": "foo.lemairepro.fr"}

```
YES! Many thanks! Thank you for your time
