### ISSUE TITLE
Multi geo setting LetsEncrypt challenge not working

### ISSUE THREAD

**Issue by metalmini** [caddyserver/certmagic#107]
## What is your question?
I am not entirely sure if this is right place to ask for help but i am trying to deduce possible issues and maybe you can point me in the right direction.

Anyway, i have followed [this tutorial](https://laravel-news.com/unlimited-custom-domains-vapor) for unlimited domains and it helps us spread out ssl certs over multiple Caddy instances. This works great btw! Very happy with that!

But, there is an issue with the creation of new certificates after we added a second caddy server in a different geo. The moment that the challenge stage starts I see the following in the logfile:

``caddy[17085]: [test.testdomain.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://test.testdomain.com/.well-known/acme-challenge/XXXXXXG8ERB8zCTORnayig9pczWfB4uduDjDEXXXXXX: Timeout during connect (likely firewall problem), url:``

If i stop Caddy on one server, this problem solves itself after some time.

## What have you already tried?
Tried it with one server, works like a charm.
Two servers, no dice.
Two servers, shutting one down when in the request loop, works (eventually).

**Comment by francislavoie** [comment]
What version of Caddy are you using? What storage plugin?

**Comment by mholt** [comment]
Hmm yeah, how can we reproduce this? Let's Encrypt is reporting a failure to connect to `http://test.testdomain.com/` so make sure to also verify your DNS and load balancing rules.

**Comment by metalmini** [comment]
Hi @francislavoie & @mholt 👋 

I am using Caddy version v2.2.1 with the caddy.storage.dynamodb that I downloaded from the download page.

Reproducing this should be pretty straightforward, but you will have to spin up two ec2 instances and a Global Accelerator. Of course I don't want to force Amazon products on you guys.

I have checked the load balancer and i can't find any reason why this setup should not work. Also the two Caddy servers, it is pretty straight forward and everything should work in a cluster, so im pretty surprised this doesn't work. DNS is working correctly left it all untouched for this weekend but still experiencing the same issues.

And as i said, if i shutdown one of the Caddy servers, it does work.

**Comment by mholt** [comment]
Caddy instances never actually talk to each other (currently) so shutting one down shouldn't affect another instance, let alone connectivity to other instances. I'm 99% sure that it's a misconfiguration on the Amazon side. If you can come up with a reproducible test case without Amazon, then this would be easier to fix. I'm not ruling out it could be a bug in CertMagic, but given the variety of successful production deployments CertMagic already has -- including on Amazon infrastructure, at quite some scale -- I'm not convinced there's a bug as serious as this without more evidence/information.

**Comment by metalmini** [comment]
This is a pretty specific use case which I probably couldn't reproduce without AWS. I agree that debugging this without a clear case is quite difficult. I also need something to hold onto. There are allot of elements in play and im trying to figure out what is going wrong.

I get a timeout on the challenge. Is there a way i can check if this is a working url?

**Comment by metalmini** [comment]
For somebody that might stumble upon this issue in need of some assistance; I have followed the tutorial linked in the issue every step of the way. In the end i opened up port 80 on the Global Accelerator because letsEncrypt could reach that url to pass the challenge. This worked for us, and it makes sense. 

I'm closing this issue because its pretty specific and debugging this in a different environment just takes to much time. Thanks for the replies.
