### ISSUE TITLE
Broken dependency klauspost/cpuid

### ISSUE THREAD

**Issue by jpincas** [caddyserver/certmagic#112]
Hi there - I believe this dependency was very recently refactored and is now breaking certmagic master (line 330, crypto.go).

**Comment by mholt** [comment]
Why do you think this? What are you trying to do? What commands are you running? What is your code? What are the errors?

**Comment by jpincas** [comment]
Sorry. It's compilation that is broken. Line 330, `crypto.go` refers to a method `AesNi()` in `klauspost/cpuid` that has been removed.

**Comment by francislavoie** [comment]
certmagic shouldn't be using cpuid v2 yet 🤔

The `AesNi()` method was removed in https://github.com/klauspost/cpuid/commit/43f4c41326096a3d90b250136a41d7e0c46bbcd8

When upgrading to v2 though, looks like it should be changed to `cpuid.CPU.Supports(cpuid.AESNI)`.

**Comment by mholt** [comment]
Yeah, I'm not sure what the problem is. CertMagic compiles fine because it does not use v2 of cpuid.

**Comment by cryptopragmatic** [comment]
I can confirm that this issue still persists. Here's how to reproduce it:

Install latest version of go.

Run `go get github.com/caddyserver/certmagic`.

This is the output:

```
anon@server1:~/go$ go get github.com/caddyserver/certmagic
# github.com/caddyserver/certmagic
src/github.com/caddyserver/certmagic/crypto.go:336:14: cpuid.CPU.AesNi undefined (type cpuid.CPUInfo has no field or method AesNi)
```

**Comment by mholt** [comment]
@cryptopragmatic CertMagic is not a command, it is a library. Please ensure you are in a Go project, as usual: https://golang.org/doc/code.html
