### ISSUE TITLE
Tweaking requests to DNS challenge providers

### ISSUE THREAD

**Issue by cameronelliott** [caddyserver/certmagic#115]
I am trying to understand how I can adjust the requests to the providers
when using Certmagic.

Say, for example, I want to specify the addresses for an A or AAAA record for Duckdns.
With this providers API, to do so means tweaking the query params used for setting the TXT record.

It doesn't look like the current Duckdns libdns implementation supports this. (hey, I am thrilled there is an implementation at all!! :)

But it looks like I could implement this change simply by adding another field to the 'Provider' struct,
similar to the APIToken or OverrideDomain fields of that struct, and add the code to drop the values into the Url
as is done for those fields.

So, my big concern, *was* that I could not get the IP=x.x.x.x fields to Duckdns without changes to Certmagic,
but it looks like that is not the case.

I can get implement IP=x.x.x.x support myself in libdns/duckdns just like OverrideDomain is implement.

Okay, groovy, kudos on a very well defined interface. 🥇 

There is not a concrete question here, except maybe an observation that I didn't find any docs on this, just figured it out wandering around the code. So maybe something to consider writing a note for new libdns users.

Please let me know if you have any suggestions about tweaking the libdns providers in such a way.

Anyway, excited this appears to be so well done.

**Comment by mholt** [comment]
Thanks for the feedback. As I don't use DuckDNS, I don't really understand the question myself, and this looks like it might be more suited for libdns/duckdns repos, rather than having anything to do with CertMagic specifically ... so if it's alright I'm going to close this as it's not really actionable, but feel free to correct me if I'm wrong. Thanks, happy new year!

**Comment by francislavoie** [comment]
I don't think I really understand what you're asking, but you're saying you want to set the A or AAAA records with the DuckDNS plugin? You can already do this by using the lib directly:

https://github.com/libdns/duckdns/blob/cd405ff644b966cd5d2cad276b5cb2d99366ab74/client.go#L63

pseudocode:

```
provider := &duckdns.Provider{
	APIToken: "topsecret",
}

record := libdns.Record{
	Type:  "A",
	Name:  "example.duckdns.org",
	Value: "1.2.3.4",
}

_, err := provider.SetRecords(ctx, "example.duckdns.org", []libdns.Record{record})
```
