### ISSUE TITLE
Use certmagic command for replacing the current `srv.ListenAndServe()` 

### ISSUE THREAD

**Issue by mohamadaqibabas** [caddyserver/certmagic#120]
## What would you like to have changed?

Ability to use `certmagic` as a replacement of `srv.ListenAndServe()` instead of just the current `http.ListenAndServe("<port>", mux)`

## Why is this feature a useful, necessary, and/or important addition to this project?

As I know, the good practice is to use some functionalities in `http.Server{}` such as timeouts to prevent slowloris attack, eg [gorilla/mux slowloris](https://github.com/gorilla/mux#graceful-shutdown) and [cloudflare http timeouts guide](https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/).
However, currently when I construct the `srv:=http.Server{ // timeouts, etc }`, I cant use the certmagic command with it.

**Comment by mholt** [comment]
Thanks for the request, but CertMagic's `HTTPS()` method does this for you already.
