### ISSUE TITLE
Combining certmagic with a local CA to enable HTTPS on localhost

### ISSUE THREAD

**Issue by aeneasr** [caddyserver/certmagic#124]
## What is your question?

I would like to use certmagic with a local provider (e.g. smallstep/truststore) in order to have TLS support on localhost. This would be analogous to caddytls/internalissuer.

## What have you already tried?

I've tried setting up certmagic on localhost which obviously does not work:

```
	err := certmagic.HTTPS([]string{"localhost"}, router)
```

I have also tried extracting the logic of caddyserver, but the module concept and lifecycle make it quite difficult to understand which values need to be initialized when and where. Some of those approaches included using `caddytls.InternalIssuer` without much luck.

I also tried embedding caddy v2 into the projects, which however would add bloat to the binaries as only a tiny fraction of what caddy provides would be needed.

## Include any other information or discussion.

At github.com/ory, many services rely on HTTPS. Making services HTTPS per default without going through the pain of skipping TLS verification would be a big bonus. To make this work on the developer's machine, using a "self-issued" but trusted CA would be the key.

Thank you for any help and the great project!

**Comment by aeneasr** [comment]
For more context, I think this thread could help: https://caddy.community/t/consuming-caddy-v2-local-pki-in-another-go-program/11871/6

In summary: this is currently not easily possible with certmagic, but it would be possible to extract logic from caddy - with refactoring involved.

**Comment by mholt** [comment]
Hmm, you'd probably need to implement an `Issuer` that integrates with a CA, or some sort of managed PKI. Caddy has facilities for those, so that's why it was implemented in Caddy. It's probably not a good fit for the core of CertMagic (since PKI goes out of scope of managing certificates), but I could certainly see it being implemented in another repo just fine.

**Comment by 89z** [comment]
https://github.com/caddyserver/certmagic/issues/25
