### ISSUE TITLE
Cannot install certmagic on M1 mac

### ISSUE THREAD

**Issue by watjurk** [caddyserver/certmagic#126]
## What version of the package are you using?
v0.13.0

## env:
- MacBook Pro (13-inch, M1, 2020) (macOS Big Sur Version 11.2.3, 20D91)
- go version go1.16.3 darwin/arm64

## What are you trying to do?
Go get certmagic

## What steps did you take?
Run `go get github.com/caddyserver/certmagic`

## What did you expect to happen, and what actually happened instead?
I expected to install certmagic as normal but instead I got an error:
```
github.com/caddyserver/certmagic/crypto.go:292:14: cpuid.CPU.AesNi undefined (type cpuid.CPUInfo has no field or method AesNi)
```

## How do you think this should be fixed?
Sorry I have no idea

## Please link to any related issues, pull requests, and/or discussion
None

**Comment by mholt** [comment]
Should be fixed with https://github.com/caddyserver/certmagic/pull/125 -- please give that PR a try and let me know how it goes!

**Comment by watjurk** [comment]
Yep it works, thanks a lot!
