### ISSUE TITLE
Support 63+ character requests

### ISSUE THREAD

**Issue by ColinChartier** [caddyserver/certmagic#130]
## What would you like to have changed?
We use certmagic to generate certificates of the form (branch name).demo.example.com for ephemeral environments, but the branch name can sometimes be long enough that the domain is >63 characters
It'd be great if we could include two SANs, where the common name is just demo.example.com (or whatever) and the second SAN is the whole (branch name).demo.example.com to circumvent the 63 character common name restriction.

## Why is this feature a useful, necessary, and/or important addition to this project?
It wouldn't necessarily have to be a very big change, just adding a fixed "base domain" to the config object to always be the common name, and would avoid problems like "NewOrder request did not include a SAN short enough to fit in CN"

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
N/A

## Please link to any relevant issues, pull requests, or other discussions.
N/A

**Comment by ColinChartier** [comment]
Example domain that doesn't currently work: https://www.adding-new-fields-pt-2-1978653611.testing.demo.example.com/

**Comment by ColinChartier** [comment]
https://github.com/ColinChartier/certmagic/commit/1e641def214ec4e3fe360434ead82ff70acc8f0d sort of works, but the certificate isn't served (I think because the cache uses ",'.join(sans) right now)

**Comment by mholt** [comment]
CertMagic does not set CommonName, so this is not a CertMagic problem.
