### ISSUE TITLE
Support IP identifiers in TLS-ALPN challenge

### ISSUE THREAD

**Issue by mholt** [caddyserver/certmagic#133]
Continuing discussion [from here](https://github.com/smallstep/certificates/issues/410#issuecomment-854229977).

**Comment by hslatman** [comment]
Quick solution is to add the following at the beginning of the `getChallengeInfo` function:

```go
if IsReverse(identifier) > 0 {
    identifier = ExtractAddressFromReverse(identifier)
}
```

Functions as defined [here](https://github.com/coredns/coredns/blob/053c4d5ca1772517746a854e87ffa971249df14b/plugin/pkg/dnsutil/reverse.go#L13) could be copied over or imported.

**Comment by mholt** [comment]
Thanks! Can you help me understand what would be involved for the not-so-quick fix you suggested?

> Using the ARPA domain as the key for the lookup is another solution.

**Comment by hslatman** [comment]
I try to check it out by the end of this week. I think the changes aren't going to be really big, but may need some consideration regarding backward compatibility for an already running instance/cluster. Then again, this is about challenges, which are temporary values, so it may not be that much of a problem.

**Comment by mholt** [comment]
Awesome, thank you!

> but may need some consideration regarding backward compatibility for an already running instance/cluster

Maaaaybe, but these are purely internal changes, I would be surprised if it broke anything even currently running. I'll take a look at the delta and let you know. :+1:

**Comment by hslatman** [comment]
Opened the PR: #139
