### ISSUE TITLE
ManageAsync silently fails on bad hostname, whereas ManageSync fails loudly.

### ISSUE THREAD

**Issue by cameronelliott** [caddyserver/certmagic#140]
## What version of the package are you using?
647f27cf265e6f72b6f043ac52ba34f01bb5da56 or latest

## What are you trying to do?
use ManageAsync(...) successfully

## What steps did you take?
...
err = magic.ManageAsync(context.Background(), []string{"foo.bar:443"})
*This was a mistake on my part! I should not have included the port number*

I found out after debugging, this is *not* an issue when using ManageSync() as the error gets propagated back up (of course).

## What did you expect to happen, and what actually happened instead?
I would expect an error to get printed to stdout, or something.
The issue is totally hidden, and it seems as if certmagic is just 'hung'.
In fact the issue is still hidden when you set ACMEManager.Logger to a zap.Logger.
But, the issue will be revealed when you set ACMEManager.Logger to a named zap.Logger with the name 'obtain'.
(That took me a while to figure out)

## How do you think this should be fixed?
Good question. Error reporting for async code can be tricky to make obvious.
I would think printing serious failures from the CA to os.Stderr would be warranted, or an io.Writer or whatever
would make sense.

## Important Note
I am only using `ManageAsync()` because it offers more control over how and when to get the user to acknowledge the CA's terms.
There is little that can be done to control the terms dialog from `ManageSync()`.
If the package using certmagic had a bit more control of how and when to get user acknowledgement,
I would switch back to `ManageSync()` in a heartbeat.

This would mean I would submit a PR to allow controlling this behavior.
*Would there be interest in reviewing a PR to allow disabling forced user terms and email collection?*
(my software has command-line flags for both)
I know, if I were the Certmagic author, I might be reluctant to allow this,
but I would also be a bit conflicted considering there is 100 million plus Docker downloads in which probably 99.9% of the created instances, no user is reviewing the output or entering and email address.

## Bonus: What do you use CertMagic for, and do you find it useful?
I'm using Certmagic to build an easy to use WebRTC SFU

**Comment by mholt** [comment]
What's the code to reproduce the bug?

**Comment by cameronelliott** [comment]
I'm attaching an example program: main.go, go.mod, go.sum in the zip
I've also attached a short video to demonstrate the issue.



[Archive.zip](https://github.com/caddyserver/certmagic/files/6743638/Archive.zip)

https://user-images.githubusercontent.com/868689/124024633-52167700-d9a4-11eb-8023-6bb5a96a6bc5.mov

**Comment by mholt** [comment]
Thanks, will look into this soon

**Comment by cameronelliott** [comment]
After thinking about this, maybe passing in an io.Writer for error messages to ManageAsync would be one way of getting notifications about problems.
Also, the only reason I am using ManageAsync and not ManageSync is because it provides more control over how/when to get user buy-in for CA terms. If ManageSync had more flexibility here, I wouldn't need the Async version.
(I wonder if removing ManageAsync and asking callers to create their own goroutine might be a good way to have users of ManageSync do async models. (I don't understand the use cases of ManageAsync well, though))

Just some thoughts.

**Comment by mholt** [comment]
@cameronelliott I'm not having the same behavior you're describing.

Obviously, without setting a logger, there is no output. This is expected.

Setting a logger that is NOT named "obtain":

```go
	l, err := zap.NewDevelopment()
	if err != nil {
		log.Fatal(err)
	}

	magic := certmagic.New(cache, certmagic.Config{
		// any customizations you need go here
		Logger: l,
	})
```

shows the complete error in gross detail:

```
$ go run main.go 
2021-07-12T15:23:21.305-0600    INFO    obtain  certmagic@v0.14.1-0.20210616191643-647f27cf265e/config.go:450   acquiring lock  {"identifier": "example.com:443"}
2021-07-12T15:23:21.324-0600    INFO    obtain  certmagic@v0.14.1-0.20210616191643-647f27cf265e/config.go:473   lock acquired   {"identifier": "example.com:443"}
2021-07-12T15:23:21.331-0600    DEBUG   obtain  certmagic@v0.14.1-0.20210616191643-647f27cf265e/config.go:512   trying issuer 1/1       {"issuer": "acme-staging-v02.api.letsencrypt.org-directory"}
2021-07-12T15:23:21.520-0600    ERROR   obtain  certmagic@v0.14.1-0.20210616191643-647f27cf265e/config.go:537   could not get certificate from issuer   {"identifier": "example.com:443", "issuer": "acme-staging-v02.api.letsencrypt.org-directory", "error": "HTTP 400 urn:ietf:params:acme:error:rejectedIdentifier - Error creating new order :: Cannot issue for \"example.com:443\": Domain name contains an invalid character"}
github.com/caddyserver/certmagic.(*Config).obtainCert.func2
        /home/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1-0.20210616191643-647f27cf265e/config.go:537
github.com/caddyserver/certmagic.doWithRetry
        /home/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1-0.20210616191643-647f27cf265e/async.go:106
github.com/caddyserver/certmagic.(*Config).obtainCert
        /home/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1-0.20210616191643-647f27cf265e/config.go:572
github.com/caddyserver/certmagic.(*Config).ObtainCertAsync
        /home/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1-0.20210616191643-647f27cf265e/config.go:427
github.com/caddyserver/certmagic.(*Config).manageOne.func1
        /home/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1-0.20210616191643-647f27cf265e/config.go:332
github.com/caddyserver/certmagic.(*jobManager).worker
        /home/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1-0.20210616191643-647f27cf265e/async.go:73
2021-07-12T15:23:21.520-0600    ERROR   obtain  certmagic@v0.14.1-0.20210616191643-647f27cf265e/async.go:120    will retry      {"error": "[example.com:443] Obtain: [example.com:443] creating new order: request to https://acme-staging-v02.api.letsencrypt.org/acme/new-order failed after 1 attempts: HTTP 400 urn:ietf:params:acme:error:rejectedIdentifier - Error creating new order :: Cannot issue for \"example.com:443\": Domain name contains an invalid character (ca=https://acme-staging-v02.api.letsencrypt.org/directory)", "attempt": 1, "retrying_in": "1m0s", "elapsed": "196.121559ms", "max_duration": "720h0m0s"}
github.com/caddyserver/certmagic.doWithRetry
        /home/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1-0.20210616191643-647f27cf265e/async.go:120
github.com/caddyserver/certmagic.(*Config).obtainCert
        /home/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1-0.20210616191643-647f27cf265e/config.go:572
github.com/caddyserver/certmagic.(*Config).ObtainCertAsync
        /home/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1-0.20210616191643-647f27cf265e/config.go:427
github.com/caddyserver/certmagic.(*Config).manageOne.func1
        /home/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1-0.20210616191643-647f27cf265e/config.go:332
github.com/caddyserver/certmagic.(*jobManager).worker
        /home/matt/go/pkg/mod/github.com/caddyserver/certmagic@v0.14.1-0.20210616191643-647f27cf265e/async.go:73
^Csignal: interrupt
```

So I'm not sure I can validate your bug report.

> Also, the only reason I am using ManageAsync and not ManageSync is because it provides more control over how/when to get user buy-in for CA terms.

Can you explain in more detail? What do you mean by "more control"? The two functions are identical except that Async assumes runnning in the background, so it won't prompt the user to agree to the terms. In either case, you should be taking care of that at the application level.

**Comment by cameronelliott** [comment]
Matt, you are absolutely right, the error is visible without needed a logger named 'obtain',
when using zap.NewDevelopment()
I was using a logger instantiated using zap.NewExample(), maybe that was a bad course of action,
I'm not very knowledgeable about the zap package.


But the unnamed logger vs an 'obtain' logger wasn't my main concern. (sorry if I didn't communicate that well)


My main concert is with without a logger, the error is totally masked and hidden.
Like in the screenshot:

<img width="1280" alt="Screen Shot 2021-07-16 at 12 50 12 PM" src="https://user-images.githubusercontent.com/868689/126001458-6bf34881-5d8e-4878-a589-ff7691f2e47c.png">

But maybe having the issue present when a properly created (zap.NewDevelopment()) logger is sufficient.

On the topic of ManageAsync vs ManageSync, 
I am using ManageAsync, not ManageSync, because with ManageSync() 
if the flags are as such:
```		
	myACME := certmagic.NewACMEManager(magic, certmagic.ACMEManager{
		CA:     certmagic.LetsEncryptStagingCA,
		Email:  "",
		Agreed: true,
	})
```

, if Email is blank, even if Agreed is `true`, the terms & conditions prompt will be displayed and block for input.
Maybe that is by design?
Or would you consider a PR to allow bypassing the terms & conditions prompt if Agreed is `true`, even if Email is "" ?

**Comment by mholt** [comment]
> My main concert is with without a logger, the error is totally masked and hidden.

This is not surprising, since ManageAsync runs in the background, the only reasonable place to put output is in the logger. (Spewing stuff to stdout/stderr could interfere with the application.) If there is no logger, there will be no output. :man_shrugging: 

> , if Email is blank, even if Agreed is true, the terms & conditions prompt will be displayed and block for input.
> Maybe that is by design?

Yep, because synchronous execution implies a user is present. Asynchronous means the program is running in the background.

When running in the background, always be sure to figure out necessary prerequisites before starting the task. (This isn't specific to CertMagic, it's expected/good practice for asynchronous applications in general.)
