### ISSUE TITLE
Go get error for different repository

### ISSUE THREAD

**Issue by yueqianlong** [caddyserver/certmagic#141]
D:\goProject\src>go get -u -v github.com/micro/micro
go get: github.com/mholt/certmagic@v0.8.3 updating to
        github.com/mholt/certmagic@v0.14.0: parsing go.mod:
        module declares its path as: github.com/caddyserver/certmagic
                but was required as: github.com/mholt/certmagic

How to resolve the proplem?

**Comment by francislavoie** [comment]
The micro project should update its dependency to use the new organization name. The change was done a long time ago.

**Comment by yueqianlong** [comment]
now is the latest versions. but the proprem still

**Comment by francislavoie** [comment]
Either way, this is not a problem with this project. Please open an issue with the micro project.
