### ISSUE TITLE
Go1.16.8 -> Go1.17.1 causes: "tls: client requested unsupported application protocols ([h2 http/1.1])"

### ISSUE THREAD

**Issue by cameronelliott** [caddyserver/certmagic#145]
## What version of the package are you using?
 v0.14.5

## What are you trying to do?
Run existing working code with a new version of Go, 1.17.1, previously used 1.16.8

## What steps did you take?
Ran certmagic code working under Go1.16.8  with Go1.17.1

## What did you expect to happen, and what actually happened instead?
HTTPS requests no longer work, with error:
"tls: client requested unsupported application protocols ([h2 http/1.1])"

It seems this issue affected another Go Http server:
https://github.com/traefik/traefik/issues/8376
I think the important point is:
> go 1.17, which enforces strict TLS APLN checking by default

## How do you think this should be fixed?
Not sure.

## Bonus: What do you use CertMagic for, and do you find it useful?
I use certmagic for WebRTC signalling and the IETF WISH draft: 
https://datatracker.ietf.org/wg/wish/documents/

**Comment by mholt** [comment]
Hm, I don't understand: is your client not negotiating HTTP, or what? Like what is the client sending if not `h2` or `http1/1.`? What is the code to reproduce this?

**Comment by cameronelliott** [comment]
[certmagic145.zip](https://github.com/caddyserver/certmagic/files/7198093/certmagic145.zip)

Here is the reproducer.
This example works as expected under Go1.16.8


Running this on MacOS with go1.17 or go.17.1 results in this:
```bash
curl -v https://kego.com
curl: (35) error:14004460:SSL routines:CONNECT_CR_SRVR_HELLO:reason(1120)
```

```bash
go run .
event tls_handshake_started
event tls_handshake_completed
2021/09/20 12:06:10 http: TLS handshake error from 192.168.86.1:54446: tls: client requested unsupported application protocols ([h2 http/1.1])
```

I think the link to the Traefik issue explains the changes in go1.17+ that are causing the issue.

Thanks for your cool software, Matt.

**Comment by mholt** [comment]
Thanks for the reproducer code.

However, I think this is working as expected. `TLSConfig()` returns a TLS config that has `NextProtos` set to `acme-tls/1`. As documented, this is a vanilla TLS configuration that is set up with what is needed to serve managed certificates and solve the TLS-ALPN ACME challenge. It doesn't make any assumptions about what protocols you're serving after TLS. Hence, it doesn't add the `h2` or `http/1.1` protocols. It is supposed to be customized if you want to serve specific protocols (this is unchanged, despite Go's recent enforcement of the RFC).

To serve HTTPS, we have a higher-level function you can use, `HTTPS()`, that customizes the NextProtos for you:

https://github.com/caddyserver/certmagic/blob/07f7d0dec12e0c032d3ac543b89e047f3b52108e/certmagic.go#L94-L95

Our [README does demonstrate this](https://github.com/caddyserver/certmagic/blob/master/README.md#advanced-use), but I admit we could make it clearer for HTTPS use cases specifically.

**Comment by mholt** [comment]
I just pushed a commit that clarifies the usage and necessity of NextProtos in the docs/comments.
