### ISSUE TITLE
New method: ManageSyncContext() to take a context.Context ? 

### ISSUE THREAD

**Issue by cameronelliott** [caddyserver/certmagic#146]
## What would you like to have changed?
I suggest the creation of a method: `ManageSyncContext(ctx context.Context, domainNames []string) error`

Just like ObtainCertSync(..) and RenewCertSync(..) do take a `context.Context` and are cancellable,
it seems like there should be a way to cancel a manage sync operation.

## Why is this feature a useful, necessary, and/or important addition to this project?
ManageSync() creates a default context.Context inside the function, rather than taking it as a parameter.

It it generally useful to be able to cancel long-running or IO bound methods in Go, and using a context.Context is
generally how this is done.
The `ManageAsync()` method does in-fact take a `context.Context`.

I don't really like using ManageAsync() as a good alternative, I find it difficult to detect when the CA rejects requests, in my experience, it means you must capture & dig through Uber Zap debug logs to understand what when wrong,
and capturing these events and parsing them is complicated and error prone. In an async manner.
#140 

**The vast majority (if not all) of the [Go Standard Library](https://pkg.go.dev/std) methods that take `context.Context` are synchronous, not async, and they find it useful to accept a `context.Context` because it provides the ability to cancel long-running operations.**
(Thus a `context.Context` does not need to be associated only with async methods, as certmagic has done for ManageSync/ManageAsync)
(I will also note that `certmagic.ObtainCertSync(..)` and `certmagic.RenewCertSync(..)` do take a `context.Context` so they are cancellable)

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
Actually, browsing the code, it kind of looks like I can use `ClientCredentials(...)` as an effective workaround. Crazy!

### Thanks
Also, thanks to @mholt @francislavoie, and all the other devs that have Caddy/Certmagic the massively useful tools that they are. If my project takes off, it will be because I stand on the shoulders of giants. :)

**Comment by mholt** [comment]
That's a good point, especially since our `ObtainCertSync()` and `RenewCertSync()` methods already do take a context.Context, so... guess it makes sense for `ManageSync()` to take a context too.

> Also, thanks to @mholt @francislavoie, and all the other devs that have Caddy/Certmagic the massively useful tools that they are. If my project takes off, it will be because I stand on the shoulders of giants. :)

You're welcome :+1:

**Comment by cameronelliott** [comment]
@mholt 
I suggested ManageSyncContext(), because adding a context to ManageSync() would be breaking for a lot of people.

I won't submit a PR, unless you think it's helpful?, I hope you will choose to add a method someday. :)

**Comment by francislavoie** [comment]
@cameronelliott I asked that same question here: https://github.com/caddyserver/certmagic/commit/1bbe11e2914b8487f2c55ba72108844133dbd203#r56974241, Matt answered

**Comment by mholt** [comment]
@cameronelliott I just added it in 1bbe11e. You should be good to go.

We've had about 14-15 breaking changes so far, that's why we're pre-1.0. No worries.
