### ISSUE TITLE
Certificates for raw IP addresses from ZeroSSL?

### ISSUE THREAD

**Issue by ghost** [caddyserver/certmagic#148]
Apparently you can get TLS certificates for raw IP address from ZeroSSL, so why doesn't caddy do it? Or is this a mistake on ZeroSSL's end 😅? (you can't get a cert for an IPv6 and they still assume dns is a thing 😆)

**Comment by rwv** [comment]
I saw a Go project for ZeroSSL ip cert. 
https://github.com/tinkernels/zerossl-ip-cert
Maybe there is an update?

**Comment by francislavoie** [comment]
@rwv that uses ZeroSSL's REST API, not ACME. But they may have changed their ACME to support it as well?

**Comment by mholt** [comment]
If someone has a chance to try it and post the output here, we can update CertMagic accordingly if ZeroSSL has in fact updated things.

**Comment by eqoram** [comment]
+1 would really appreciate certificates for raw IP addresses

**Comment by JoNilsson** [comment]
> +1 would really appreciate certificates for raw IP addresses

another +1 for this.

**Comment by coolaj86** [comment]
@mholt Didn't you implement this for DASH?

Or was it just the ability to exec out to call a script, and then that script could all the ZeroSSL API with the IP address?

**Comment by mholt** [comment]
I think it was the exec thing.

IP certs are only issued through ZeroSSL's API with a paid API key.

**Comment by coolaj86** [comment]
> I think it was the exec thing.

Where are the docs for how to use that?

**Comment by mholt** [comment]
I think it's $10/mo for _unlimited_ 90-day certs, not $10/mo _per certificate_... so comparing to $10/year pricing before Let's Encrypt isn't really fair IMO.

I am having a hard time recalling exactly what we talked about, but the issuer logic is an interface: https://pkg.go.dev/github.com/caddyserver/certmagic#Issuer

Hmm, I need to recall our previous conversations in more detail. Or just write a several-line Go function that shells out to a script.

**Comment by coolaj86** [comment]
Here's what GPT and I came up with as a first pass (probably some mistakes):

```go
type ShellScriptIssuer struct {
	ScriptPath string
}

func (s *ShellScriptIssuer) Issue(ctx context.Context, request *x509.CertificateRequest) (*IssuedCertificate, error) {
	tempFile, err := os.CreateTemp("", "certificate_*.pem")
	if err != nil {
		return nil, fmt.Errorf("failed to create temporary file: %v", err)
	}
	defer os.Remove(tempFile.Name())

        csrDER, err := x509.CreateCertificateRequest(rand.Reader, request, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal certificate request to DER: %v", err)
	}

	// Create a PEM block for the certificate request
	pemBlock := &pem.Block{
		Type:  "CERTIFICATE REQUEST",
		Bytes: csrDER,
	}

	// Encode the PEM block to []byte
	pemBytes := pem.EncodeToMemory(pemBlock)
        pemString := string(pemBytes)

        // calls ./path/to/foo '/path/to/write/cert' 'example.com' 'example.com,www.example.com', 'AB....'
	cmd := exec.CommandContext(ctx, s.ScriptPath, tempFile.Name(), request.Subject, request.DNSNames, pemString)
	err = cmd.Run()

	// Check the exit status of the shell script
	if err != nil {
		return nil, fmt.Errorf("failed to execute shell script: %v", err)
	}

	// Read the contents of the temporary file
	certificateBytes, err := os.ReadFile(tempFile.Name())
	if err != nil {
		return nil, fmt.Errorf("failed to read certificate from temporary file: %v", err)
	}

	// Create the IssuedCertificate instance
	issuedCert := &IssuedCertificate{
		Certificate: certificateBytes,
		Metadata:    nil, // Add metadata if needed
	}

	return issuedCert, nil
}
```

**Comment by mholt** [comment]
I think that's the basic idea, yeah. Definitely vet that for correctness but it's the right basic idea.
