### ISSUE TITLE
Certificate stored before private key

### ISSUE THREAD

**Issue by sam-lord** [caddyserver/certmagic#149]
## What version of the package are you using?

Latest release, 0.15.1

## What are you trying to do?

Create a wrapper around the storage (which also implements `certmagic.Store`) so that I can upload certificates to a CDN whilst storing the certs in a compatible way otherwise.

## What steps did you take?

Implemented a new store which just passes all of the function calls to the storage passed in. Added some more logic to `Store` so that certificates and private keys are uploaded to the CDN. 

## What did you expect to happen, and what actually happened instead?

Private key to be generated first,  as the private key has to exist for the certificate to function. The CDN in use rejects requests to add a certificate if the private key for the certificate is missing. 

## How do you think this should be fixed?

- Swap the order that these two files are uploaded (in `crypto.go`. I can't see any way that this could negatively impact the compatibility. 

## Bonus: What do you use CertMagic for, and do you find it useful?

So exciting to be using the project in my app. Hopefully will be able to announce something soon!

**Comment by mholt** [comment]
The private key is always created before the certificate, it's impossible to do it any other way.

To clarify, you're referring instead to the order in which the assets are saved, though, right, i.e. the order of elements in this slice?

https://github.com/caddyserver/certmagic/blob/1c89882bc5908f74f8c5aaf38af64f2820004861/crypto.go#L148-L163

If so, I guess we can make that change. Shouldn't be a big deal.
