### ISSUE TITLE
 x509: certificate signed by unknown authority 

### ISSUE THREAD

**Issue by zzxap** [caddyserver/certmagic#151]
renewing certificate: [mydomain] Renew: [mydomai] creating new order: provisioning client: performing request: Get "https://acme-v02.api.letsencrypt.org/directory": x509: certificate signed by unknown authority (ca=https://acme-v02.api.letsencrypt.org/directory)

can not start  certmagic.HTTPS

**Comment by mholt** [comment]
Make sure your system CA roots are properly installed.

(This isn't a problem in CertMagic, so I'm going to close the issue.)
