### ISSUE TITLE
Add context propagation to the Storage interface

### ISSUE THREAD

**Issue by chaudyg** [caddyserver/certmagic#154]
## What would you like to have changed?

The `Storage` interfaces do not support context propagation. Only the `Lock` method does.  This would require changing the method signature for the `Storage` interface: 
```go
// Implementations of Storage must be safe for concurrent use.
type Storage interface {
	// Locker provides atomic synchronization
	// operations, making Storage safe to share.
	Locker

	// Store puts value at key.
	Store(ctx context.Context, key string, value []byte) error

	// Load retrieves the value at key.
	Load(ctx context.Context, key string) ([]byte, error)

	// Delete deletes key. An error should be
	// returned only if the key still exists
	// when the method returns.
	Delete(ctx context.Context, key string) error

	// Exists returns true if the key exists
	// and there was no error checking.
	Exists(ctx context.Context, key string) bool

	// List returns all keys that match prefix.
	// If recursive is true, non-terminal keys
	// will be enumerated (i.e. "directories"
	// should be walked); otherwise, only keys
	// prefixed exactly by prefix will be listed.
	List(ctx context.Context, prefix string, recursive bool) ([]string, error)

	// Stat returns information about key.
	Stat(ctx context.Context, key string) (KeyInfo, error)
}
```

## Why is this feature a useful, necessary, and/or important addition to this project?

Propagating the context would be useful when using a remote storage (mainly for context cancellation). For example with the s3 storage:

https://github.com/ss098/certmagic-s3/blob/efad3a48d4edfbe2fee64e9c4d04195603822b07/s3.go#L144

**Comment by mholt** [comment]
Are you finding that those calls are taking a long time? (S3 is not a suitable storage backend, because it does not provide atomic operations, by the way, you will run into problems.)

Lock can definitely block for some time, but other calls shouldn't in practice.

**Comment by hairyhenderson** [comment]
@mholt FYI Georges is my teammate and I encouraged him to file this 😉

> Are you finding that those calls are taking a long time?

In the general case it's useful to be able to cancel _any_ I/O, especially with remote back-ends, regardless of how much time they may take. There are cases where an operation may simply block indefinitely, and so we need to be able to timeout/cancel/trigger a retry within a reasonable amount of time.

In our case we're working on a GCS backend (which does provide acceptable consistency), and similar to the linked S3 backend we're finding ourselves unable to propagate the context in a satisfactory way.

I suggested this get filed as certmagic is still pre-1.0 and so this is IMO the right opportunity to change the interface to allow for propagation.

**Comment by mholt** [comment]
Ok. I did think about doing this, but doing so will break all the storage implementations.

I suppose we can do this, but we'll need to file issues -- maybe even PRs that fill in a `context.TODO()` if there isn't one in their code already -- with all known storage implementations.

**Comment by hairyhenderson** [comment]
> but doing so will break all the storage implementations.

This is 0.x still, so there's no promise of compatibility, right? 😉

I think opening issues/PRs is fair. Is sticking with the list at https://github.com/caddyserver/certmagic/wiki/Storage-Implementations enough?

I'm willing to help open issues/PRs with these implementations to help smooth things through, and I might be able to convince @chaudyg to lend a hand as well.

Given you're amenable to this, I'll issue a PR to make the change.

**Comment by francislavoie** [comment]
> This is 0.x still, so there's no promise of compatibility, right? wink

Sure, but everyone who builds Caddy with any of the storage plugins would have breaking builds unless the version of certmagic in Caddy and the one the storage plugin uses match. It's a wrench.

**Comment by mholt** [comment]
Yeah, that should be fine, CertMagic is still pre 1.0 for these reasons.
