### ISSUE TITLE
could not find the start of authority

### ISSUE THREAD

**Issue by hongyi-zhao** [caddyserver/certmagic#161]
I use certmagic via [a thin wrapper](https://github.com/anderspitman/certgrabber) but failed as follows:

```
$ login_token="ID,Token"
$ certgrabber -domain bp.hyddns.xyz -provider dnspod -token $login_token -challenge-type dns-01
Getting cert for domain: bp.hyddns.xyz
bp.hyddns.xyz: obtaining certificate: [bp.hyddns.xyz] Obtain: [bp.hyddns.xyz] solving challenges: presenting for challenge: could not determine zone for domain "_acme-challenge.bp.hyddns.xyz": could not find the start of authority for _acme-challenge.bp.hyddns.xyz.: NOERROR (order=https://acme-v02.api.letsencrypt.org/acme/order/324767840/48975851400) (ca=https://acme-v02.api.letsencrypt.org/directory)
```
See [here](https://github.com/boringproxy/boringproxy/issues/113#issuecomment-998538589) for related discussion. Any hints for fixing this problem?

Regards,
HZ

**Comment by francislavoie** [comment]
Certmagic makes DNS queries to find an SOA record so that we know what the "base domain" is, so it can tell the DNS plugin the base domain/zone.

Real quick, I tried looking for an SOA for your domain, and it looks fine: https://mxtoolbox.com/SuperTool.aspx?action=soa%3ahyddns.xyz&run=toolpage

So I figure whatever DNS server your system is configured to use isn't resolving it 🤷‍♂️

**Comment by hongyi-zhao** [comment]
I tried with Google DNS as follows:

```
werner@X10DAi-00:~$ dig +short SOA bp.hyddns.xyz @8.8.8.8
www.hyddns.xyz.
werner@X10DAi-00:~$ dig +short SOA hyddns.xyz @8.8.8.8
donald.dnspod.net. freednsadmin.dnspod.com. 1640510300 3600 180 1209600 180
```
Can these results be used as evidence for the problems discussed here?

**Comment by francislavoie** [comment]
Those results look correct 🤷‍♂️

**Comment by francislavoie** [comment]
Thanks for that detailed explanation! Fascinating. Glad you figured it out!
