### ISSUE TITLE
DNS Validation (AWS R53) fails if TXT key _acme-challenge.<domain.com> exists, is that the intended flow?

### ISSUE THREAD

**Issue by karngyan** [caddyserver/certmagic#162]
## What version of the package are you using?
v0.15.1

## What is your question?

I use certmagic to generate and renew certs automatically for an SMTP Relay. I generate wildcard domains for the same, along with DNS Validation using route53 (leveraging libdns).

- When a new certificate is supposed to be generated or validated, if there is a record in AWS R53 with TXT key: `_acme-challenge.<domain.com>`, it should override the record/delete the old record and append the new one and continue validation.
- `certmagic` returns an error and also exits generating certs for any other domain in the array.
- Is this the intended flow?
- Does it affect any other use cases?

## What have you already tried?

This is the current code. I could go ahead and handle deletion on my end, but was just curious to understand the reason for this approach.

```golang
func autoManageAndRenewCerts() {

	// make sure aws keys have access to respective route53 hosted zone
	domains := []string{"*.domain1.com", "*.domain2.com"}
	certificateAuthority := setting.CertmagicCertificateAuthority
	certStoragePath := setting.CertmagicStoragePath
	// renew check time, default is 10 minutes as check is lightweight
	renewCheckInterval := 10 * time.Minute

	cache := certmagic.NewCache(certmagic.CacheOptions{
		GetConfigForCert: func(cert certmagic.Certificate) (*certmagic.Config, error) {
			return &certmagic.Config{
				// any customization based on cert
			}, nil
		},
		RenewCheckInterval: renewCheckInterval,
	})

	r53p := &route53.Provider{
		AccessKeyId:     setting.CertmagicIAMAccessKey,
		SecretAccessKey: setting.CertmagicIAMSecretKey,
	}

	err := r53p.NewSession()
	if err != nil {
		fmt.Println("failed initializing route53 client for certmagic")
		return
	}

	magic := certmagic.New(cache, certmagic.Config{
		Storage: &certmagic.FileStorage{Path: certStoragePath},
	})

	letsEncryptACME := certmagic.NewACMEManager(magic, certmagic.ACMEManager{
		CA:     certificateAuthority,
		Email:  "email@domain.com,
		Agreed: true,
		DNS01Solver: &certmagic.DNS01Solver{
			DNSProvider: r53p,
		},
	})

	magic.Issuers = []certmagic.Issuer{letsEncryptACME}

	go func() {
		err = magic.ManageSync(context.Background(), domains)
		if err != nil {
			fmt.Println("failed to manage sync certmagic", err.Error())
		}
	}()

}
```

**Comment by mholt** [comment]
Shouldn't the proper handling of the DNS records be the job of the DNS provider plugin? I don't think there's anything wrong in CertMagic here. The DNS provider plugin should always make sure it sets the proper record for the challenge, and if there's an error, we do properly return instead of continuing because there was an error.

**Comment by karngyan** [comment]
> Shouldn't the proper handling of the DNS records be the job of the DNS provider plugin? I don't think there's anything wrong in CertMagic here. The DNS provider plugin should always make sure it sets the proper record for the challenge, and if there's an error, we do properly return instead of continuing because there was an error.

Makes sense. I'll move over to libdns.
