### ISSUE TITLE
Revoked Certificate

### ISSUE THREAD

**Issue by Mojo90** [caddyserver/certmagic#167]
Hi there, 
since today I unfortunately have a revoked certificate for my server.
I use it with: `err := certmagic.HTTPS([]string{"ipmanagement.develapp.me"}, router)`
yesterday it worked as it should and I am not sure how to fix? Can you help me how to fix that? Using now since I guess two years without problem but now when I go to the server I get the error message: `2022/02/01 12:03:13 http: TLS handshake error from 195.202.50.240:54303: EOF`

**Comment by mholt** [comment]
Let's Encrypt just revoked a bunch of certificates. How are you using CertMagic? What version?

**Comment by Mojo90** [comment]
I see, yes I updated it and now it is fixed again and working as it should - perfect thank you :)!

**Comment by mholt** [comment]
Oh good, I literally only fixed-it-fixed-it like 2 hours before you posted that.
