### ISSUE TITLE
Any error satisfies ErrNotExist

### ISSUE THREAD

**Issue by chaudyg** [caddyserver/certmagic#168]
## What version of the package are you using?
2f78e52

## What are you trying to do?

I am working on a module implementing the Storage interface. While testing my code, I noticed that any error satisfies the [ErrNotExist interface](https://github.com/caddyserver/certmagic/blob/master/storage.go#L280-L283). The following code is always true regardless of the error:

```
if _, ok := err.(certmagic.ErrNotExist); ok {
    // this is always true!
}
```

## What steps did you take?

Here is an example to illustrate the issue
https://go.dev/play/p/u-eYGshvKDp

## How do you think this should be fixed?
`ErrNotExist` should not be an interface.

**Comment by mholt** [comment]
Oops. Thanks for pointing that out. :sweat_smile: That's kinda embarrassing.

When I first wrote CertMagic, the `io/fs` package did not exist (heh). Nor did `errors.Is()`. Now, though, I wonder if we could use [`fs.ErrNotExist`](https://pkg.go.dev/io/fs#ErrNotExist) instead.

**Comment by mholt** [comment]
@chaudyg Can you give #170 a look when you have a chance?
