### ISSUE TITLE
What is going on with AWS EFS?

### ISSUE THREAD

**Issue by mholt** [caddyserver/certmagic#169]
We keep getting reports that Caddy/CertMagic sometimes return errors with regards to lock files. These are files that are created during certificate management so that only 1 instance in a cluster manages a certificate at any given time. A file is atomically created on disk (it must not already exist), then its contents are updated every few seconds with a new JSON payload containing the current timestamp. This is how we detect and prevent stale locks, which happen if a process is forcefully terminated, and which would deadlock other instances indefinitely.

These errors seem to suggest that the lock files are empty or corrupted or incomplete:

- https://caddy.community/t/keeping-lock-file-fresh-error-im-getting-from-the-logs/15053?u=matt  `[ERROR] Keeping lock file fresh: unexpected end of JSON input - terminating lock maintenance (lockfile: /mnt/efs/caddy_data/locks/issue_cert_www. userDomain .pl.lock`
- https://caddy.community/t/how-to-eliminate-downtime-in-a-caddy-cluster/15063?u=matt `obtaining certificate: unable to acquire lock 'issue_cert_eight.greenbongo.com': decoding lockfile contents: EOF`
- https://github.com/caddyserver/caddy/issues/3954#issuecomment-753801739 `obtaining certificate: EOF` (user determined it was a permissions problem)

And several other forum posts or issues in the past have also reported EOF or JSON errors.

So... what is going on with EFS? Does it have problems with write consistency? Even after adding Sync() calls to the lock file code, these errors persist.

When we update a lock file, we open it using O_RDWR, then read the file, then truncate the file to 0, then seek to position 0, then write the updated contents and sync and close the file:

https://github.com/caddyserver/certmagic/blob/2f78e527561dfdc9f14b7618a265571f206f6be4/filestorage.go#L301-L338

I wonder if EFS has trouble with truncating/syncing? I have no idea.

**Comment by hairyhenderson** [comment]
I've not used EFS in over a year, so my memory is a bit sketchy, but I do remember EFS has a few quirks (even considering the quirks that NFS tends to have in general)... Notably, you're not guaranteed read-after-write will always behave consistently. 

From what I understand about a bit more NFS googling, the only consistency you can really be assured of is "close-to-open consistency" - i.e. after a file is closed, the next open will contain the data written before that previous close. There's also a fair amount of caching involved to speed up perceived performance, which might get in the way too.

From reading the [AWS docs on EFS consistency](https://docs.aws.amazon.com/efs/latest/ug/how-it-works.html#consistency), I _think_ that maybe if you open with `syscall.O_DIRECT` you might get slightly better consistency. There's also a note about attribute caching in one of the [troubleshooting](https://docs.aws.amazon.com/efs/latest/ug/troubleshooting-efs-general.html#custom-nfs-settings-write-delays) docs that may be relevant - maybe that's affecting something too?

**Comment by hairyhenderson** [comment]
Another related side-note - when looking at the docs for https://pkg.go.dev/github.com/zbiljic/go-filelock I noticed this:

> This used to call syscall.Flock() but that call fails with EBADF on NFS. An alternative is lockf() which works on NFS but that call lets a process lock the same file twice. Instead, use Linux's non-standard open file descriptor locks which will block if the process already holds the file lock.

I'm not totally clear if this would be helpful at all, but in code (for Linux anyway) this ends up in a call to [`syscall.FcntlFlock`](https://pkg.go.dev/syscall#FcntlFlock), here: https://github.com/zbiljic/go-filelock/blob/master/filelock_linux.go#L119... 🤷‍♂️

**Comment by mholt** [comment]
Thanks Dave! That's very interesting. A [tweet by Miek](https://twitter.com/miekg/status/1492170520405676032) points out that EFS is mounted as NFS, so... quite likely loses all the same guarantees NFS lacks.

[Another by ffkiv](https://twitter.com/ffkiv/status/1492202184586395650) says that posix assumptions are violated in distributed environments. (makes sense)

Still, I'm not quite as convinced that those are relevant here, since what seems to be happening is that writes are not persisted/consistent after close; this doesn't appear to be about the O_EXCL flag. And as you said, Dave, it sounds like EFS should be able to guarantee that if we write a file, sync it, and close it, when we open it later it will read what we wrote.

I wonder if the problem would go away if we got rid of use of Truncate() and Seek() and instead just opened the file twice. If anyone wants to test this, I'd happily make a branch we can tinker with!

**Comment by hairyhenderson** [comment]
> I wonder if the problem would go away if we got rid of use of Truncate() and Seek() and instead just opened the file twice.

hmm... That might be enough, as the only thing that you need to read the file for is the `Created` field, which shouldn't get modified anyway.

The fact that the file seems corrupt (`unexpected end of JSON input`) might point to multiple writers attempting to update the file at the same time... Without first acquiring a lock on the file that's totally possible with NFS (especially when you start considering write caches are involved too), so you might need to do that _anyway_...

**Comment by kalmi** [comment]
I think it might be that the keepLockfileFresh goroutine keeps running despite the lock being released, because by the time the sleep is over, somebody might have acquired the lock, and then os.IsNotExist(err) would once again be false.

Having multiple keepLockfileFresh goroutines running for the same lock would explain these errors.

**Comment by mholt** [comment]
> I think it might be that the keepLockfileFresh goroutine keeps running despite the lock being released

That should not be the case. What evidence is there of that being true?

Anyway, it sounds like the consensus is that NFS does not properly implement the file system APIs, and so these symptoms are indicative of bugs in NFS, not in CertMagic.

**Comment by mohammed90** [comment]
> Anyway, it sounds like the consensus is that NFS does not properly implement the file system APIs, and so these symptoms are indicative of bugs in NFS, not in CertMagic.

You're right here. It's the same reason [cited by SQLite](https://www.sqlite.org/faq.html) for recommending against putting SQLite file on an NFS filesystem:

> this locking mechanism might not work correctly if the database file is kept on an NFS filesystem. This is because fcntl() file locking is broken on many NFS implementations. You should avoid putting SQLite database files on NFS if multiple processes might try to access the file at the same time.

**Comment by mholt** [comment]
That's really good to know! I didn't realize sqlite encountered the same issues. Thanks for pointing that out @mohammed90 .
