### ISSUE TITLE
Implementing custom on-demand logic

### ISSUE THREAD

**Issue by anderspitman** [caddyserver/certmagic#176]
First, I have to say certmagic continues to be invaluable and part of the backbone of boringproxy. Thanks for this package!

## What is your question?

I want my server to support wildcard domains, and get certs on-demand. This is working, but as mentioned in the docs it opens up DoS. I'm wanting to implement a simple limiting scheme that allows a given number of certs to be issued per wildcard (maybe 10 or 100), then refuses to issue more after that and sends a warning to the administrator.

Basically what I need to make this work is a way to query certmagic to see how many subdomains it currently has for a given wildcard. Does such an option exist already?

Or is there a better way to accomplish what I'm doing? Obviously I'd prefer to whitelist domains as they are provided by the user, but since boringproxy is a reverse proxy, it needs to be able to pass through control over a wildcard to an upstream server, while still handling TLS termination itself.

## What have you already tried?

I've looked through the docs and didn't see any obvious way to check how many certs already exist in memory/on disk for a given wildcard. Maybe `Cache.AllMatchingCertificates()`?

## Bonus: What do you use this package for, and does it help you?

It handles all cert management for [boringproxy](https://boringproxy.io/).

**Comment by francislavoie** [comment]
You just need to configure a `DecisionFunc`: https://github.com/caddyserver/certmagic#on-demand-tls

**Comment by anderspitman** [comment]
Yes I am doing that and it's working for getting the certs, but inside `DecisionFunc` I need to determine whether there are already too many certs for a given wildcard. It would be very undesirable and error-prone to have to track this state myself, especially since all the information already exists in the certmagic `Storage` backend. I just need a way to query it.

**Comment by mholt** [comment]
Interesting requirement...

> how many subdomains it currently has for a given wildcard

What do you mean exactly by "it currently has"? I could think of several variants on this that could all fit that definition... 🤔

**Comment by anderspitman** [comment]
Let's say that I have a wildcard A/AAAA record (*.example.com) pointing at my certmagic server with on-demand enabled. Over time a.example.com, b.example.com, and c.example.com are visited, and certmagic gets certs for them each in turn. I'm trying to make a way to limit this to some maximum number of certs, without tracking that information myself. If there's a way for me to query how many certs certmagic has obtained for *.example.com, that would solve the problem.

**Comment by mholt** [comment]
I mean if it's really that simple, you could probably just count that, right? What's so error prone about counting them for your needs?

But you can see what CertMagic has its in cache: https://pkg.go.dev/github.com/caddyserver/certmagic#Cache.AllMatchingCertificates

Or, if you need to see what is in storage, just call `List()` and look for the names you're interested in: https://pkg.go.dev/github.com/caddyserver/certmagic#Storage

**Comment by anderspitman** [comment]
I agree it seems a bit extreme. The reason is because I'm working on an API where the storage backend is injected by the user, ie anything that needs to be stored permanently will be part of that API. It would be really nice if I didn't need to add hooks for storing subdomains.

`Storage.List` looks promising. I'll give that a shot, thanks :+1:

**Comment by mholt** [comment]
If you're already dealing with storage modules, you could also write a wrapper over storage and count the `Store()`s for the keys you're interested in.

**Comment by anderspitman** [comment]
That's a good idea as well
