### ISSUE TITLE
OnDemand for certificate renewal

### ISSUE THREAD

**Issue by volendavidov** [caddyserver/certmagic#180]
## What would you like to have changed?
Adding OnDemand for certificate renewal, in a way similar to how the OnDemand function for new certificates works.

## Why is this feature a useful, necessary, and/or important addition to this project?
The ability to control when a certificate should be renewed would have been very useful before the revocation of TLS-ALPN-01  certificates on 28 January 2022. For users with large number of certificates, relying on automatic replacement of revoked certificates wouldn't have worked as Let's Encrypt's thresholds would have been quickly hit, even with adjusted rate limits and such users had to start renewing certificates in advance. Having such a feature would have made it easier to renew certificates in a way controlled by the user instead of adjusting RenewalWindowRatio which provides less flexibility.
In addition, after the revocations were completed, it was necessary to start renewing certificates again with the normal limits imposed by Let's Encrypt's.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
Editing directly after:
https://github.com/caddyserver/certmagic/blob/f83201861a3710cd9e062ea86954928854a0b57b/handshake.go#L469-L473
and passing additional parameter to `renewDynamicCertificate` to force the renewal in:
https://github.com/caddyserver/certmagic/blob/f83201861a3710cd9e062ea86954928854a0b57b/handshake.go#L589

**Comment by mholt** [comment]
Thanks for writing up a feature request. I appreciate the thought behind it, but I don't think this is a good fit for the project.

To clarify some things and explain why:

- Revoked certificates are already automatically renewed (assuming OCSP stapling not disabled). CertMagic will detect revocations and replace certificates with a new one before serving a REVOKED response (which it won't do). Assuming the latest versions, users shouldn't be manually replacing revoked certificates when using CertMagic.
- New ACME extension ARI will usurp user preferences by having the ACME CA recommend when to renew a certificate.
- To forcefully renew a certificate anyway, simply delete it from storage.

**Comment by francislavoie** [comment]
For ref, latest draft of the ACME ARI proposal https://datatracker.ietf.org/doc/html/draft-aaron-acme-ari-02
