### ISSUE TITLE
clientHello.Context undefined (type *tls.ClientHelloInfo has no field or method Context)

### ISSUE THREAD

**Issue by dropthemasquerade** [caddyserver/certmagic#181]
## What version of the package are you using?
v0.16.0

## What are you trying to do?
```
func Test_goModule(t *testing.T) {
	type args struct {
		mod *debug.Module
	}

	var mod debug.Module
	tests := []struct {
		name string
		args args
		want *debug.Module
	}{
		{
			"test",
			args{
				&mod,
			},
			&debug.Module{},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := goModule(tt.args.mod); !reflect.DeepEqual(got, tt.want) {
				t.Errorf("goModule() = %v, want %v", got, tt.want)
			}
		})
	}
}
```

## What steps did you take?

```
# github.com/caddyserver/certmagic
../../../go-workspace/pkg/mod/github.com/caddyserver/certmagic@v0.16.0/handshake.go:755:64: clientHello.Context undefined (type *tls.ClientHelloInfo has no field or method Context)
note: module requires Go 1.17

Compilation finished with exit code 2
```

## What did you expect to happen, and what actually happened instead?
It should run case pass or failed

## How do you think this should be fixed?

Make sure `type *tls.ClientHelloInfo has no field or method Context` 

## Please link to any related issues, pull requests, and/or discussion
The caddy is using it here https://github.com/caddyserver/caddy/blob/master/modules/caddytls/connpolicy.go#L185

## Bonus: What do you use CertMagic for, and do you find it useful?
I just try to run case test on caddy project, but got failed, because this reason.

**Comment by francislavoie** [comment]
What version of Go are you using? As of v0.16.0, certmagic requires Go 1.17.

**Comment by mholt** [comment]
Almost certainly an old Go version; closing, feel free to continue discussion if upgrading Go does not solve the problem.
