### ISSUE TITLE
Should the root certificate be delivered by the server?

### ISSUE THREAD

**Issue by firefly-serenity** [caddyserver/certmagic#183]
## What is your question?

Using Certmagic, the webserver is delivering the whole chain of certificates to the client (root, intermediate and server). Several discussions and articles state that it is preferable to not deliver the certificate of the root ca, since it should always be present in the trust store of the client. I am curious why you chose to handle it the way you did.

## Include any other information or discussion.

Here are some links about the topic:
https://github.com/golang/go/issues/40510
https://whatsmychaincert.com/
https://success.qualys.com/discussions/s/question/0D52L00004Tntq6SAB/should-the-root-certificate-go-on-the-server

## Bonus: What do you use this package for, and does it help you?

I really like the package and I am using it in several projects. Thanks a lot for creating and maintaining this awesome project!

**Comment by mholt** [comment]
Glad you are using CertMagic!

Can you show me an example where CertMagic is delivering the full chain?

**Comment by mholt** [comment]
Thanks. CertMagic uses the certificate chain as provided by the CA. I would check with the CA and ask why they are providing the root certificate if you feel it is not necessary. :+1:

(Closing, but feel free to continue discussion if needed!)
