### ISSUE TITLE
Fallback ACME provider

### ISSUE THREAD

**Issue by mbardelmeijer** [caddyserver/certmagic#184]
## What would you like to have changed?

We have certmagic configured with 1 ACME provider (LetsEncrypt). We prefer to configure it with ZeroSSL as a fallback for if LetsEncrypt ratelimits have been met or it's not available.

## Why is this feature a useful, necessary, and/or important addition to this project?

This adds extra redundancy to the certificate process.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

Caddy supports this natively.

## Please link to any relevant issues, pull requests, or other discussions.
Perhaps this is already possible and I just don't know how to configure it :)

**Comment by mholt** [comment]
Just add [`caddytls.ZeroSSLIssuer`](https://pkg.go.dev/github.com/caddyserver/caddy/v2/modules/caddytls#ZeroSSLIssuer) to your config: https://pkg.go.dev/github.com/caddyserver/certmagic#Config.Issuers

**Comment by mbardelmeijer** [comment]
Pff dunno how I missed that. Thanks!
