### ISSUE TITLE
Using Certmagic with pebble (local ACME Server) how to skip certificate verification?

### ISSUE THREAD

**Issue by mariuskimmina** [caddyserver/certmagic#191]
## What is your question?
I have [Pebble](https://github.com/letsencrypt/pebble) running on localhost and want certmagic to use it as a CA. Currently I am running into the following error when calling `ObtainCertSync`:

```
[example.com] Obtain: registering account [mailto:test@test.test] with server: provisioning client: performing request: Get "https://localhost:14000/dir": x509: certificate signed by unknown authority
```
So, Cermagic is trying to use my local Pebble Server, which is good, but it's trying to verify it's certificate which won't work. How do I dislabe this check?

## What have you already tried?
I am using a certmagic config with `InsecureSkipVerify`:

```
acmeConfig := certmagic.NewDefault()
acmeConfig.TLSConfig().InsecureSkipVerify = true
```

But had no luck with that.

**Comment by mholt** [comment]
I used Pebble to develop CertMagic, so I know this works. Let me help!

`acmeConfig.TLSConfig()` returns a TLS config for you to use as a _server_; it doesn't configure the ACME client. To clarify, `certmagic.NewDefault()` does not return an ACME config, it returns a CertMagic config. A CertMagic config is for servers, not ACME clients.

What you probably want to do is configure the `DefaultACME` value, which is an ACME issuer config: https://pkg.go.dev/github.com/caddyserver/certmagic#DefaultACME

You can't disable cert verification here, but you can set `TrustedRoots` to include your Pebble server CA: https://pkg.go.dev/github.com/caddyserver/certmagic#ACMEIssuer.TrustedRoots

And then you'll be good to go.

**Comment by mariuskimmina** [comment]
Got it to work! thank you for your help.
