### ISSUE TITLE
Storage Implementation Bug

### ISSUE THREAD

**Issue by edwardwc** [caddyserver/certmagic#192]
## What version of the package are you using?

CertMagic 0.16.1

## What are you trying to do?

I've forked an S3 Storage repository (you can find it here: https://github.com/edwardwc/better-s3). After implementing it into `certmagic.Default.Storage`, CertMagic seemed able to probe the bucket:

```
2022/07/23 14:55:24 Better S3: Storing for rw_test_3648290488268453755
2022/07/23 14:55:24 Better S3: Loading for rw_test_3648290488268453755
2022/07/23 14:55:24 Better S3: Deleting for rw_test_3648290488268453755
```
(the names correlate to the methods used)

However, there seems to be an issue when a certificate does not exist:

```
2022/07/23 14:55:24 Better S3: Locking for issue_cert_{domain}.com
2022/07/23 14:55:24 Better S3: Exists for certificates/acme-v02.api.letsencrypt.org-directory/{domain}/{domain}.crt
2022/07/23 14:55:24 Better S3: Loading for certificates/acme-v02.api.letsencrypt.org-directory/{domain}/{domain}.key
```

Now, after doing some debugging I was able to conclude the Load function in this case did, indeed, return an error. I am unsure as to why the Load function was called in the first place: when Exist returned false. The same program has no problem generating SSL certificates when using the default file storage.

**Comment by edwardwc** [comment]
Issue fixed! It turns out when Load is called and an object does not exist, you have to return `fs.ErrNotExist`. Have a great day!

**Comment by mholt** [comment]
Glad you figured it out! I'll keep an eye on your progress. What is better about your S3 implementation? (There are a few out there but they have trouble with locking because S3 does not provide atomic operations; I think one of them uses DynamoDB for that... but yeah. It's tricky.)

> Have a great day!

Thank you :blush: You too
