### ISSUE TITLE
incorrect time comparisons using the NotAfter timestamp

### ISSUE THREAD

**Issue by benburkert** [caddyserver/certmagic#197]
## What version of the package are you using?

$ caddy version
v2.5.2 h1:eCJdLyEyAGzuQTa5Mh3gETnYWDClo1LjtQm2q9RNZrs=

## What are you trying to do?

Use certmagic with caddy to automatically renew certificates with certmagic as the ACME client.

## What steps did you take?

Here is my Caddyfile:

```
{
        debug
        acme_ca {$ACME_DIRECTORY_URL}
        acme_eab {
                key_id {$ACME_KID}
                mac_key {$ACME_HMAC_KEY}
        }
        admin off
        storage_clean_interval 10m
        renew_interval 1m
}
{$DNS_NAME} {
  respond "Hello There!"
}
```

## What did you expect to happen, and what actually happened instead?

I expected certmagic to track a certificates validity until the end of its life, but certmagic drops the last (fractional) second from the certificate life due to the imprecise definition and granularity of `Not After` in X.509 certificates. [More background and discussion on this issue here](https://community.letsencrypt.org/t/discussion-of-2021-06-08-certificate-lifetime-incident-valid-for-an-extra-one-second/153469). The tl;dr is that the certificate is valid for the entire second of the `Not After` value, so a certificate with a `Not After` value of `2022/01/01 23:59:59` is still valid at `2022/01/01 23:59:59.999`.

This is causing the following log message to appear in the caddy logs, because the certificate's `Not After` is compared to the OCSP's `nextUpdate` (which does not have the same imprecision issue), without accounting for the different granularities.

```
tls.cache.maintenance   stapling OCSP   {"identifiers": ["foo.sample.internal"], "error": "invalid: OCSP response for [foo.sample.internal] valid after certificate expiration (-1s)"}
```

certmagic should be aware of this issue when doing time comparisons, for example in the OCSP check and cache expiration timestamp.

## How do you think this should be fixed?

I'm happy to open a PR to fix the time comparison issue. If so, would you prefer to have a `Certificate.ValidBefore time.Time` field with the timestamp that can be used for comparison, or update all comparisons to account for the extra `(1 * time.Second)`?

## Please link to any related issues, pull requests, and/or discussion

https://community.letsencrypt.org/t/discussion-of-2021-06-08-certificate-lifetime-incident-valid-for-an-extra-one-second/153469

## Bonus: What do you use CertMagic for, and do you find it useful?

Testing out automated certificate rotation with caddy/certmagic.

**Comment by mholt** [comment]
Just curious, what are you doing that requires the last fraction of a second of a certificate's lifetime? They should be renewed 30% before that.

**Comment by benburkert** [comment]
Just testing at the moment, and trying to make sure an ACME server handles cert renewals properly. I've found Caddy to be an excellent test client because it already handles cert renewals based on OCSP checks. This -1 second isn't breaking anything, just causing spurious log messages because of the `NotAfter`/`NextUpdate` comparison.

OK, I'll start a PR to add the `NotAfter` method.

**Comment by mholt** [comment]
@benburkert Gotcha. Yeah, that sounds like a good way to handle this then. Thank you!
