### ISSUE TITLE
Question: DNS-01 Challenge results in multiple DNS requests?

### ISSUE THREAD

**Issue by mariuskimmina** [caddyserver/certmagic#202]
## What is your question?
When using the DNS-01 Challenge, is it normal that the DNS Server receives multiple (up to 4) requests for `_acme-challenge`?  

## What have you already tried?
I tried skimming through the RFC, couldn't really find any mention of it.
I also read the documentation from Let's Encrypt but couldn't find any mention of this either. 
So I am wondering if this is normal ACME-Challenge behaviour, or If there is something strange going on.

## Bonus: What do you use this package for, and does it help you?
For context, I am trying to develop a CoreDNS Plugin that can automate tls certificates when CoreDNS itself is the autoritative DNS Server for the Domain. Currently testing this out with my own domain. While it seems to work (most of the time), I sometimes only receiv 1 or 2 of these requests and then the Challenge fails - and I am currently trying to figure out why. 

```
[INFO] plugin/tls: Obtaining TLS Certificate, may take a moment
[INFO] plugin/tls: Answering ACME DNS request:_acme-challenge.ns1.subdomain.mariuskimmina.com.
[INFO] plugin/tls: Answering ACME DNS request:_acme-challenge.ns1.subdomain.mariuskimmina.com.
[INFO] plugin/tls: Answering ACME DNS request:_acme-challenge.ns1.subdomain.mariuskimmina.com.
```

In cases where I only receiv 1 or 2 of these requests, the log looks like this: 
```
[INFO] plugin/tls: Answering ACME DNS request:_acme-challenge.ns1.subdomain.mariuskimmina.com.
[INFO] plugin/tls: Answering ACME DNS request:_acme-challenge.ns1.subdomain.mariuskimmina.com.
[ERROR] plugin/tls: Failed to setup TLS automatically: [ns1.subdomain.mariuskimmina.com] Obtain: [ns1.subdomain.mariuskimmina.com] solving challenge: ns1.subdomain.mariuskimmina.com: [ns1.subdomain.mariuskimmina.com] authorization failed: HTTP 400 urn:ietf:params:acme:error:dns - During secondary validation: DNS problem: SERVFAIL looking up TXT for _acme-challenge.ns1.subdomain.mariuskimmina.com - the domain's nameservers may be malfunctioning (ca=https://acme-v02.api.letsencrypt.org/directory)
```

**Comment by mholt** [comment]
Yes, some CAs like Let's Encrypt use multi-perspective validation to mitigate BGP attacks, etc: https://letsencrypt.org/2020/02/19/multi-perspective-validation.html

**Comment by mariuskimmina** [comment]
That perfectly explains what's going on here, thanks a lot! 
I'm still not sure why some of those requests don't reach me sometimes but still you really helped me out here

**Comment by mholt** [comment]
Good luck!
