### ISSUE TITLE
Feature request: automatic revoke-outdated-after-renewal

### ISSUE THREAD

**Issue by jayaddison** [caddyserver/certmagic#210]
## What would you like to have changed?
After renewal of managed certificates from an ACME CA, the ability to (optionally) revoke the previously-issued certificate with [reason code](https://datatracker.ietf.org/doc/html/rfc5280#section-5.3.1) `superseded`.

## Why is this feature a useful, necessary, and/or important addition to this project?
For single-host sites using certificates issued from an ACME CA, generally a previously-issued certificate _shouldn't_ be valid for continued use anywhere after a renewed certificate has been obtained and deployed.

It may be worth retaining and archiving previously-issued certificate material -- even so, revoking the validity of previously-issued certificates (even when they have short-expiry times) could provide additional safety (even if no compromise is known or anticipated).

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
Manually requesting revocation of previously-issued certificates with the ACME CA could be a way to handle this in the absence of an automated approach.

## Please link to any relevant issues, pull requests, or other discussions.
- https://community.letsencrypt.org/t/why-not-revoke-a-certificate-after-renewal-or-end-of-use/116216
- https://blog.mozilla.org/security/2022/05/16/revocation-reason-codes-for-tls-server-certificates/

**Comment by mholt** [comment]
Thanks for the feature request.

I have mixed feelings about this since revocation is broken in the first place.

> revoking the validity of previously-issued certificates (even when they have short-expiry times) could provide additional safety (even if no compromise is known or anticipated).

In what ways does it provide additional safety if it is not compromised or actually needing revocation in the first place?

**Comment by jayaddison** [comment]
> I have mixed feelings about this since revocation is broken in the first place.

Sure, no problem.  It'd be more code and functionality to maintain, and especially for an unclear goal I understand that it may not be worthwhile on balance.

> In what ways does it provide additional safety if it is not compromised or actually needing revocation in the first place?

Primarily it'd reduce the value of the old key material -- so it becomes less attractive for attackers to look for, and less valuable even if they obtain it.

**Comment by jayaddison** [comment]
And thank you for the swift responses - that all seems reasonable.  I might revisit this again at some point in future after thinking about it further.
