### ISSUE TITLE
Is it good practise to use certmagic inside a Dockercontainer that gets killed on a regular basis?

### ISSUE THREAD

**Issue by nilskch** [caddyserver/certmagic#217]
## What is your question?
Is it good practise to use certmagic inside a Docker Container that does not have a Volume attached to persist the Certificates? Especially during development I will redeploy the app very often (multiple times a day) and certmagic would need to fetch a certificate for the same URL very often. Is this bad practise or is this ok?

## Bonus: What do you use this package for, and does it help you?

I am working with a very lean Kubernetes Cluster and I want to manage as much as possible inside the actual app. I could also use an ingress controller in front of the actual container and do the TLS termination there, but I don't have a certificate manager installed in Kubernetes. The Kubernetes Cluster I am using is from my University and we don't want to install too much things on it because we don't want people having to maintain it.

**Comment by francislavoie** [comment]
That's definitely bad practice. You should ensure your storage is persisted.

You are subject to ACME issuer rate limits. Let's Encrypt rate limits by repeated issuance of a cert for the same domain (among other vectors). ZeroSSL doesn't rate limit at this time, but you shouldn't rely on that fact.

It you change domains, the storage will eventually get cleaned up by removing expired certificates anyway.

You could configure a different storage module if you don't want to store it on disk, e.g. Redis or some other shared filesystem.

**Comment by nilskch** [comment]
Okay makes sense, thank you very much!
