### ISSUE TITLE
newAccount() GenerateKey P256 hard-coded value

### ISSUE THREAD

**Issue by tjmullicani** [caddyserver/certmagic#223]
## What is your question?
It looks like the `newAccount()` function hard-codes the P256 KeyType when calling GenerateKey(). Before version v0.12.0, it used P384. Is it possible to have this be a user-specified KeyType, or set the value back to P384?

https://github.com/caddyserver/certmagic/blob/master/account.go#L79

## What have you already tried?
`privateKey, err := ecdsa.GenerateKey(elliptic.P384(), rand.Reader)`

## Include any other information or discussion.
[b76b76a](https://github.com/caddyserver/certmagic/commit/b76b76abfcacf44350226e59907fbdc23b31f489#diff-f6b999e59a3bf2a10e179d18a4e35d50001c51e331eb3ec18fef70e71a1643b9L65)

## Bonus: What do you use this package for, and does it help you?
https://github.com/joohoi/acme-dns

**Comment by tjmullicani** [comment]
I am trying to meet CNSA 1.0 guidance, which requires the use of curve P-384.

https://media.defense.gov/2021/Sep/27/2002862527/-1/-1/0/CNSS%20WORKSHEET.PDF

**Comment by mholt** [comment]
@tjmullicani You can replace the `certmagic.Account.PrivateKey` field with your own key, using the `NewAccountFunc` callback: https://pkg.go.dev/github.com/caddyserver/certmagic#ACMEIssuer.NewAccountFunc
