### ISSUE TITLE
Quic Support

### ISSUE THREAD

**Issue by APoolio** [caddyserver/certmagic#230]
## What is your question?
Is there any update on possibly adding support for QUIC? And is there any documentation on how to use CertMagic within my own HTTP/3 listener?

## Include any other information or discussion.
Same question was asked in 2019 but I was curious if there are any updates regarding this
https://github.com/caddyserver/certmagic/issues/42

**Comment by mholt** [comment]
What we do in Caddy is simply give the `http3.Server` the TLS config returned from CertMagic. (Same as you would an `http.Server`.) https://pkg.go.dev/github.com/quic-go/quic-go@v0.34.0/http3#Server.TLSConfig

That's the basic idea, anyway.

**Comment by APoolio** [comment]
Awesome, I figured that was the way but wasn't sure. Thanks for the quick response

**Comment by mholt** [comment]
quic* response :wink:
