### ISSUE TITLE
 How to use certmagic with iris （github.com/kataras/iris ）?

### ISSUE THREAD

**Issue by schooltech** [caddyserver/certmagic#234]
Hi, 
 How to use certmagic with iris （github.com/kataras/iris ）?

Thanks you very much

**Comment by mholt** [comment]
I don't know. That is a better question for the Iris developer.

However, I cannot in good faith recommend Iris. The developer has repeatedly stolen code, violated licenses, altered commit history, and insulted others. I remember being in the thick of it back in the day, years ago. In my own conversations with him, I tried to help in good faith to turn things around, but my advice was disregarded and the same patterns continued.

- https://github.com/the-benchmarker/web-frameworks/issues/1129
- https://github.com/avelino/awesome-go/pull/1135
- https://github.com/avelino/awesome-go/pull/1137
- https://github.com/julienschmidt/httprouter/issues/148
- https://www.reddit.com/r/golang/comments/57w79c/why_you_really_should_stop_using_iris/ (see screenshots in comments)
- https://www.reddit.com/r/golang/comments/57tmp1/why_you_should_not_use_iris_for_your_go_projects/
- https://www.reddit.com/r/golang/comments/s0381a/would_you_recommend_me_or_not_to_use_katarasiris/

I hate to dunk on an open source project but my experience with its maintainer has been repeatedly toxic. I just want to let you know for your own information.
