### ISSUE TITLE
Should Unlock() clean up things on error?

### ISSUE THREAD

**Issue by eest** [caddyserver/certmagic#235]
## What is your question?
In the documentation for https://github.com/caddyserver/certmagic/blob/master/storage.go the `Unlock()` interface is described as such:
```
// Unlock releases the lock for name. This method must ONLY be
// called after a successful call to Lock, and only after the
// critical section is finished, even if it errored or timed
// out. Unlock cleans up any resources allocated during Lock.
Unlock(ctx context.Context, name string) error
```

So it is fairly clear that there is an expectation that `Unlock()` should clean things up. What I am unsure about is what is expected if an operation done in `Unlock()` fails. Here is a sample from an etcd3-using-backend I have written (for clarity, the mutex is a https://pkg.go.dev/go.etcd.io/etcd/clientv3/concurrency#Mutex, not the standard library `sync.Mutex()` which is why it can return an error):
```
	err := mutex.Unlock(ctx)
	if err != nil {
		s.logger.Debug().Msgf("Unlock(): failed releasing lockKey '%s', ", lockKey)
		// TODO(patlu): Not sure if we should clean up map here
		// or leave it. The documentation comment above states
		// "Unlock cleans up any resources allocated during
		// Lock" without regard for success or error, so for
		// now clean it up, but it also means the caller can not
		// retry Unlock() requests that failed.
		s.deleteLockFromMap(lockKey)
		return err
	}
	s.logger.Debug().Msgf("Unlock(): released lockKey '%s'", lockKey)

	// Cleanup the map entry
	s.deleteLockFromMap(lockKey)
```

So I guess the real question is, will an `Unlock()` ever be retried if it returns an error? The locks created in etcd already has a TTL attached to them, so they will eventually expire by themselves. If an `Unlock()` is not retried "cleaning things up" as I am already doing in the error path is the correct thing to do. If it can be retried however then I would need to keep things around for a later attempt.

What is expected here?

**Comment by mholt** [comment]
Hi, sorry for the late reply. Got a little busy with something else unexpectedly last week.

> So I guess the real question is, will an Unlock() ever be retried if it returns an error?

Not directly. In the case of a cert renewal, for example, those are retried upon *any* error, after a backoff period. But in general, no, we can't say or assume that Unlock will be retried. The user would probably need to just restart the process or something.

If a retry is all it takes to fix the error, though, then I think the implementation should do that.

If a TTL will automatically cause it to unlock later, then maybe just return the error -- hopefully it says something about TTL -- and then a later retry happening after the TTL would succeed in acquiring the lock. In theory.

Does that help?

**Comment by mholt** [comment]
Sounds good! Yep. Sometimes retrying to unlock doesn't make sense, it's really up to the implementation to decide that.
