### ISSUE TITLE
Release cycle

### ISSUE THREAD

**Issue by mbardelmeijer** [caddyserver/certmagic#236]
## What is your question?

Just an informing question: what's the official release cycle for this package? We're seeing a few good-to-have changes on the master branch, but as from what I can see is that is aligns with the Caddy release cycle. Perhaps a minor version can be released in an earlier stage? 

## Include any other information or discussion.
Mostly looking for https://github.com/caddyserver/certmagic/commit/6670b5e1cc545256468bb8f0e682770333349010 & https://github.com/caddyserver/certmagic/commit/53575742b6fff72be88c50e7fb402b7f5d1c5c64

**Comment by mholt** [comment]
Yeah, it usually gets tagged before a Caddy release. But I can probably tag v0.18.0.

Any reason you can't just use HEAD in the meantime?

**Comment by mbardelmeijer** [comment]
That would be great 🙏 

The primary reason is that we wish to keep a specific tagged version and upgrade whenever we have the chance to analyze the changes in a new update so that it doesn't impact our app. Using `HEAD` would be too on the "bleeding edge" for us at the moment.

**Comment by mholt** [comment]
Oh, sorry, I meant a specific commit (at current HEAD) -- that way you won't have to wait for releases :100:

But I'll get around to doing a release soon!

**Comment by mholt** [comment]
@mbardelmeijer Ok, v0.18.0 is tagged now.

**Comment by mbardelmeijer** [comment]
Thanks! :shipit:

**Comment by mholt** [comment]
@mbardelmeijer I recommend using v0.18.2 :smiley: (Caddy 2.7 beta 2 is also going out today with that tag.)
