### ISSUE TITLE
Support zerossl IP cert 

### ISSUE THREAD

**Issue by ghost** [caddyserver/certmagic#262]
## What would you like to have changed?

Support zerossl IP cert 

## Why is this feature a useful, necessary, and/or important addition to this project?

Support zerossl IP cert 

## Please link to any relevant issues, pull requests, or other discussions.
 https://github.com/tinkernels/zerossl-ip-cert

**Comment by mholt** [comment]
I haven't looked into this much recently, but does ZeroSSL support IP certs from their ACME endpoint? (Their docs say that HTTP validation is supported, which to me implies ACME support.)

**Comment by mholt** [comment]
I think their API should at least support IP certs, and support for their API is in progress.
