### ISSUE TITLE
Support customizable certificate validity period

### ISSUE THREAD

**Issue by clauverjat** [caddyserver/certmagic#263]
Note : The feature was more about Caddy than certmagic so I moved it there https://github.com/caddyserver/caddy/issues/5985 
That being said the implementation of such feature in caddy will require change in certmagic

**Comment by mholt** [comment]
I'm working on this FYI

**Comment by mholt** [comment]
This is done btw:

https://github.com/caddyserver/certmagic/blob/fa7161a1a82c12d789171a938c5125af195365cc/acmeissuer.go#L72-L77
