### ISSUE TITLE
Implement ARI

### ISSUE THREAD

**Issue by mholt** [caddyserver/certmagic#284]
[The ACME Renewal Information (ARI) spec](https://datatracker.ietf.org/doc/draft-ietf-acme-ari/) might be starting to stabilize, and [Let's Encrypt just announced](https://twitter.com/mholt6/status/1783546800366092535) that renewals complying with ARI will not be rate limited. That was my primary concern, was intentionally refusing service to clients especially during times of infrastructure strain when reliability is already questionable and the renewal window is narrowing.

This sets a good precedent going forward and hopefully other CAs who implement ARI will follow their example.

I still have [multiple](https://community.letsencrypt.org/t/thoughts-from-starting-to-play-with-ari/200276/5?u=mholt) [reservations](https://mailarchive.ietf.org/arch/msg/acme/AeJ3zJKcBF-ZUhQXJajC0bb7orI/) regarding the philosophy behind ARI, but I think it's probably worth implementing, at least with some configuration, since the policies behind ARI can still vary between CAs. For example, a CA might offer ARI, but in a way that does not actually help you ensure reliability when you comply with it. CertMagic's implementation will balance site uptime with optional protocols.

Let's Encrypt has [an article to guide the implementation of ARI](https://letsencrypt.org/2024/04/25/guide-to-integrating-ari-into-existing-acme-clients). ACMEz, CertMagic's underlying ACME library, [already supports the latest ARI draft](https://github.com/mholt/acmez/blob/master/acme/ari.go), but CertMagic will need to keep track of state and do some polling and scheduling to make ARI happen for the user.

**Comment by oliverpool** [comment]
[Tailscale Takeaways](https://letsencrypt.org/2024/05/01/ari-in-tailscale.html) could be interesting to look at (BSD-3 license).

**Comment by mholt** [comment]
This is being staged at https://github.com/caddyserver/certmagic/pull/286
