### ISSUE TITLE
Do calls to storage Load need to be Lock protected?

### ISSUE THREAD

**Issue by elee1766** [caddyserver/certmagic#296]
by contract, do calls to load need to be protected by the storage lock?

from what I see, the lock is used only to protect for simultaneous writes. it's not used to lock/protect the reader if a writer is currently writing. 

is the caller supposed to take the Lock before reading the certificate? if not, are storage Load implementations supposed to protect for concurrent read/write access?

**Comment by elee1766** [comment]
Filestore uses os.WriteFile

```
// WriteFile writes data to the named file, creating it if necessary. 

// If the file does not exist, WriteFile creates it with permissions perm (before umask); 

// otherwise WriteFile truncates it before writing, without changing permissions. 

// Since WriteFile requires multiple system calls to complete, a failure mid-operation 

// can leave the file in a partially written state. 

func WriteFile(name string, data []byte, perm FileMode) error { 

	f, err := OpenFile(name, O_WRONLY|O_CREATE|O_TRUNC, perm) 

	if err != nil { 

		return err 

	} 

	_, err = f.Write(data) 

	if err1 := f.Close(); err1 != nil && err == nil { 

		err = err1 

	} 

	return err 

}
```

if reader reads while writefile is running. it could read after open file, which truncates the file, so it will read empty.

so I think there is a race and protection is needed

**Comment by elee1766** [comment]
https://github.com/containerd/containerd/blob/main/pkg%2Fatomicfile%2Ffile.go
maybe can do what containerd does

**Comment by mholt** [comment]
> by contract, do calls to load need to be protected by the storage lock?

No; this synchronization should be handled primitively, natively/internally, within the storage mechanism. The user shouldn't have to lock for every other storage operation.

> from what I see, the lock is used only to protect for simultaneous writes. it's not used to lock/protect the reader if a writer is currently writing.

Locking is for user-scope purposes, like renewing certificates or something. So it can protect reads and writes, but what it's really for is to sync a certain operation or task that may involve multiple reads or writes.

> if reader reads while writefile is running. it could read after open file, which truncates the file, so it will read empty.

It sounds like you know a lot more about the primitives of file systems than I do :sweat_smile: Especially after our conversation in slack. We can implement improvements to the FileStorage if needed! Is it a matter of calling Sync() in more places?

**Comment by elee1766** [comment]
> > by contract, do calls to load need to be protected by the storage lock?
> 
> No; this synchronization should be handled primitively, natively/internally, within the storage mechanism. The user shouldn't have to lock for every other storage operation.
> 
> > from what I see, the lock is used only to protect for simultaneous writes. it's not used to lock/protect the reader if a writer is currently writing.
> 
> Locking is for user-scope purposes, like renewing certificates or something. So it can protect reads and writes, but what it's really for is to sync a certain operation or task that may involve multiple reads or writes.
> 
> > if reader reads while writefile is running. it could read after open file, which truncates the file, so it will read empty.
> 
> It sounds like you know a lot more about the primitives of file systems than I do 😅 Especially after our conversation in slack. We can implement improvements to the FileStorage if needed! Is it a matter of calling Sync() in more places?

i think the easiest solution is to do what containerd is doing.

instead of writing over a file, we should write a new file and attempt to copy over it. 

i will try to replicate the race condition, create a fix, and show that the race is resolved.

**Comment by mholt** [comment]
That would be a great help, thank you! :raised_hands:

**Comment by mholt** [comment]
@elee1766 We can close this right? Now that we have #300 merged

**Comment by elee1766** [comment]
yessir
