### ISSUE TITLE
When using ZeroSSL and RFC2136, the CNAME content for the validation is wrong

### ISSUE THREAD

**Issue by QuentinC** [caddyserver/certmagic#304]
Hello, 

I'm trying to move from https://github.com/caddy-dns/lego-deprecated to https://github.com/caddy-dns/rfc2136 using ZeroSSL and a Bind9 nameserver.

When the CNAME record is added, there seems to be an error in the "nsupdate" command on this line: 
https://github.com/caddyserver/certmagic/blob/1ff1ad8413424cb7f927a36d6fef29d2d024fb90/zerosslissuer.go#L149

The string "verifyInfo.CnameValidationP2" doens't contains the ending ".", so Bind9 adds the domain name part.

I'm ending with validation issues like this: 
```
{
	"cname_found":1,
	"record_correct":0,
	"target_host":"_69E344F05C4C88DC869F7F8ABDCE6702",
	"target_record":"7D4F656AA48FDFB78D15970C4C16E900.5ADEC3FAE3C500FAFD12033CA2DC1715.82A618D2F94D3C5.COMODOCA.COM",
	"actual_record":"7D4F656AA48FDFB78D15970C4C16E900.5ADEC3FAE3C500FAFD12033CA2DC1715.82A618D2F94D3C5.COMODOCA.COM.X.YZ"
}
```
where x.yz is my domain name.

For now I am unable to use ZeroSSL with RFC2136...

Best regards !

**Comment by mholt** [comment]
Go ahead and try the latest commit, and let me know please. :smiley:

**Comment by mholt** [comment]
I think you want to use `--with github.com/caddyserver/certmagic=github.com/caddyserver/certmagic@master` instead of `--with github.com/caddyserver/caddy/v2=github.com/QuentinC/caddy/v2@706dbd9c`

**Comment by mholt** [comment]
Yeah, been preparing a few enhancements before I update.
