### ISSUE TITLE
Consider simplifying the Storage interface

### ISSUE THREAD

**Issue by anderspitman** [caddyserver/certmagic#309]
## What would you like to have changed?
I think the `Storage` interface could be changed to a simple kv store, ie 

```go
type Storage interface {
        Get(key string) []byte
        Set(key string, value []byte)
        Delete(key string)
}
```

This would obviously require more work on certmagic's side, especially for `Stat`, but I think it could be done. I think you might even be able to implement `Lock` and `Unlock` with just kv but I haven't thought much about that.

## Why is this feature a useful, necessary, and/or important addition to this project?
It would make it much easier to implement new storage backends.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
I implemented the full interface.

## Please link to any relevant issues, pull requests, or other discussions.
N/A

**Comment by mholt** [comment]
I've actually thought about an interface that embeds/extends `fs.FS` -- which we would use, if it only supported _writing_ and _creating_ files. And a streaming interface might be preferable over blobs-in-memory, maybe.

I'm not sure how we could do List or Lock/Unlock with just those methods though.

**Comment by anderspitman** [comment]
You're right. For List, even a naive approach where you get all keys and then handle the paths manually still requires a GetAllKeys, and it wouldn't scale.

And when thinking through how you would implement Lock/Unlock for a filesystem, the complexity and likely bugs of that one piece would be way worse than having dedicated methods.

Also, now that I've finished my implementation and written some tests for it, it really wasn't that bad, especially given that you can ignore size and modtime in KeyInfo.

I was a bit confused by the comment above List though. I interpreted as if recursive=false, then only list direct children of key. Is that right?

**Comment by mholt** [comment]
Right, if recursive is false, then only direct children of a key should be listed.
