### ISSUE TITLE
Add support to DynamoDB as a cluster storage backend

### ISSUE THREAD

**Issue by danlsgiga** [caddyserver/certmagic#41]
## What would you like to have changed?
Add support for DynamoDB as a cluster storage backend

## Why is this feature a useful, necessary, and/or important addition to this project?
IMO, it allows people that don't want to manage a Consul cluster or shared filesystem to get the clustering feature on top of DynamoDB, which does not require much effort.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
Right now we depend on Consul being fully HA in order to get Caddy in a "clustered" way. Having it in DynamoDB will give us more peace of mind since we don't need to care about Consul's availability or any shared filesystems alternative to have a healthy Caddy running.

## Please link to any relevant issues, pull requests, or other discussions.
I can't think of one at this moment

**Comment by fillup** [comment]
Hi all, I just published a storage adapter for DynamoDB. I'd love it if you'd give it a try and give me any feedback: https://github.com/silinternational/certmagic-storage-dynamodb. It's working for me in my application so hopefully it'll work for others well too.

**Comment by danlsgiga** [comment]
This is great @fillup!! I think I can give it a try in my env.
