### ISSUE TITLE
Listing new DynamoDB storage adapter

### ISSUE THREAD

**Issue by fillup** [caddyserver/certmagic#62]
Hi @mholt, I wrote a new DynamoDB storage adapter, but before I add it to the list of known adapters I wanted to ask if you'd look it over and provide any feedback/suggestions/issues you have with it.

https://github.com/silinternational/certmagic-storage-dynamodb

Thanks!

**Comment by mholt** [comment]
Hey @fillup - thanks for contributing this, looks awesome and should be really useful!

Looks pretty good -- but I don't use DynamoDB myself so I can assess only so much. Just a couple things.

The trickiest thing usually is Lock/Unlock. I noticed that this: https://github.com/silinternational/certmagic-storage-dynamodb/blob/4e6c577f652a31ea43faf70ba3e49c29cc72f3ed/storage.go#L280 can cause a pretty deep call stack. Consider a loop here instead.

Another thing to watch out for is concurrent calls to Lock(). That method checks for existence of a lock and then creates it, using separate calls to getItem and Store. I'm worried that this is not truly atomic and that both could do the getItem check at the same time, and then both call Store, thinking they both have the lock. You'll need a way to atomically check for and create the lock together. For example, if there's some sort of "INSERT" query that fails on duplicate key, or something.

I think those are the main things that caught my attention.

I'm excited for this though! I will also be willing to make a Caddy 2 module for this. Just let me know where to submit a PR. :)

**Comment by fillup** [comment]
Thanks for the quick response. I can certainly change that to a loop instead of a recursive function. 

As for the error on a duplicate key I believe it'll just get overwritten in DynamoDB, but I'll do some further testing on that. I think DynamoDB has a transaction capability too so I'll see if that could help in this situation. 

I'm using CertMagic outside the context of Caddy so I'm not familiar with Caddy modules but I'm certainly happy to include it so others can benefit from it. Feel free to point me to an example or submit a PR on that repo.

**Comment by mholt** [comment]
@fillup Sure, a transaction sounds like a good solution if I understand them correctly. You just need some sort of atomicity guarantee from the backend.

As for a Caddy module, it's really easy -- just an adapter/wrapper over the underlying implementation so that the JSON config structure is consistent. For example, here's the module for the default file storage: https://github.com/caddyserver/caddy/blob/v2/modules/filestorage/filestorage.go -- a file like this could live in your repo, for instance.

It's simple enough that I could submit a PR to you, or you could do it yourself if you want, either way. :+1:

**Comment by danlsgiga** [comment]
If you need help testing this I can give it a try in my env

**Comment by fillup** [comment]
Thanks @danlsgiga, it's working for me but it'd be great to have confirmation from others and validation that the implementation approach works beyond my environment. 

@mholt for the Caddy module, should that be in a separate package? I see your example has an `init` function to register with Caddy so I'm imagining a separate package, but let me know for sure.

**Comment by mholt** [comment]
@fillup Doesn't have to be; if you have many users who are not also using Caddy, then a separate package makes the most sense probably.

**Comment by fillup** [comment]
I'm having an interface issue with the rename/move to caddyserver/certmagic:

```
cannot use (*DynamoDBStorage)(nil) (type *DynamoDBStorage) as type caddy.StorageConverter in assignment:
	*DynamoDBStorage does not implement caddy.StorageConverter (wrong type for CertMagicStorage method)
		have CertMagicStorage() ("github.com/caddyserver/certmagic".Storage, error)
		want CertMagicStorage() ("github.com/mholt/certmagic".Storage, error)
```

**Comment by danlsgiga** [comment]
> Thanks @danlsgiga, it's working for me but it'd be great to have confirmation from others and validation that the implementation approach works beyond my environment.

No worries. I see your implementation is to plug into CertMagic... I'm looking forward to help you get it into Caddy as a module because that will benefit me a lot.

**Comment by fillup** [comment]
Interesting, when I was running `go get -u github.com/caddyserver/caddy/v2` it would error about the certmagic being used, but when explicitly running `go get -u github.com/caddyserver/caddy/v2@169883868503c809c9ac9c8c1fe93c7deff9cd2e` I got past it and all is well now. I'll update again when I think I have a caddy module included

**Comment by mholt** [comment]
@fillup Yes, using a version `@version` in `go get` will be necessary until the stable 2.0 release, unfortunately, that's how Go modules works. For building the Caddy plugin, [xcaddy](https://github.com/caddyserver/xcaddy) may be of use to you! It lets you run caddy with your module plugged in just like `go run`.

**Comment by danlsgiga** [comment]
hey @fillup, I just realized I'm blocked to move to Caddy v2 because I depend on the caddy v1 tlsconsul plugin, which is not compatible with v2.

How is the integration of your DynamoDB storage adapter for Caddy v2?

**Comment by fillup** [comment]
Hi @danlsgiga, Matt provided a PR with the Caddy module to me yesterday and we got it merged and released. Check it out and let me know how it works for you :-) https://github.com/silinternational/certmagic-storage-dynamodb/releases/tag/1.0.0

**Comment by fillup** [comment]
@mholt has updated the wiki page and linked to my dynamodb storage adapter so I believe this issue can be closed.

**Comment by danlsgiga** [comment]
This is amazing news! Thank you for working on this!!

**Comment by danlsgiga** [comment]
My only suggestion is to improve the docs in your README to include how to import that into Caddy and a config example for it! ;)

**Comment by fillup** [comment]
@danlsgiga would you mind submitting a PR for that? Since I don't use Caddy yet myself I'm not sure what that would look like.

**Comment by mholt** [comment]
@danlsgiga There are instructions for that in the Caddy readme: https://github.com/caddyserver/caddy/#with-version-information-andor-plugins
