### ISSUE TITLE
CertificateResource.NamesKey(): result truncation seems to be discarding first 1018 bytes

### ISSUE THREAD

**Issue by renthraysk** [caddyserver/certmagic#64]
https://github.com/caddyserver/certmagic/blob/03d064592b1df40f1ea45941df3a6f9235ea858d/certmagic.go#L415

This looks like it should be... 

```result = result[:1018] + "_trunc"```

**Comment by mholt** [comment]
Oops, wow, I think you're right! Want to submit a PR and take credit for the fix? :D If not that's fine I'll do it soon...
