### ISSUE TITLE
*tls.ClientHelloInfo has no field or method SupportsCertificate

### ISSUE THREAD

**Issue by hb-chen** [caddyserver/certmagic#68]
## What version of the package are you using?
v0.10.12

## What did you expect to happen, and what actually happened instead?

go version `1.13.8` func `hello.SupportsCertificate` undefined, required go version 1.14.2
https://github.com/golang/go/commit/dd0173845f939dc532e8e8348b8360914dbca216

```
# github.com/caddyserver/certmagic
../../../../../pkg/mod/github.com/caddyserver/certmagic@v0.10.12/handshake.go:201:18: hello.SupportsCertificate undefined (type *tls.ClientHelloInfo has no field or method SupportsCertificate)
```

**Comment by mholt** [comment]
As you found, Go 1.14 is required.
