### ISSUE TITLE
How to manage multiple accounts with certmagic/lego

### ISSUE THREAD

**Issue by RO-29** [caddyserver/certmagic#70]
## What is your question?

Hello, I need to manage more than 300 domains (which is the rate limit per 3 hours) and may need to have multiple accounts to issue/renew the cert. 

My question is about the private key generated for each account, can I use the same private key for multiple accounts or each account must have a separate private key.

Is this private key only used when issuing or renewing a cert?

## What have you already tried?

I have tried single account and it works well

## Include any other information or discussion.

I don't really fall into large hosting provider limit so LE will most likely reject my request
https://docs.google.com/forms/d/e/1FAIpQLSetFLqcyPrnnrom2Kw802ZjukDVex67dOM2g4O8jEbfWFs3dA/viewform

## Bonus: What do you use this package for, and does it help you?

I am really inspired by his package and thx for your wonderful work, I am using lego go wrapper but would likely migrate to certmagic soon

**Comment by mholt** [comment]
CertMagic maps account email to ACME account key in storage (but CAs do not, they only care about distinct keys). You would need to generate a new private key to use multiple accounts.

But, I don't think that is a great idea, for a couple reasons: it's more complicated, and it adds pressure/stress on the CA's infrastructure.

> I don't really fall into large hosting provider

I mean, if you need to get 300 certificates in a 3 hour timeframe, that's pretty large scale hosting tbh. I would just fill out their form. They're very good about their processes.
