### ISSUE TITLE
Support for multi-SAN certificate ?

### ISSUE THREAD

**Issue by MichaelMure** [caddyserver/certmagic#75]
I'm currently assessing CertMagic to see if it could solve the problem we have for a project. So far it looks great.

Due to the limitation that wildcard certificate can only cover a single level of subdomain and not the domain itself, we are in a situation where we would need to generate a non-trivial number of certificates. Being able to generate (by using lower level functions) certificates with a bunch of domains at once would definitely help regarding the LetsEncrypt rate limiting.

Reading the code, it looks to me that CertMagic assume in a few places that managed certificate have a single SAN, notably during renewal. Is that correct ?

How hard would it be to allow generation and renewal of multi-SAN certificate ? Would it be something you agree to have in your code-base ?

**Comment by mholt** [comment]
Hi, please see previous discussion here: https://github.com/caddyserver/certmagic/pull/49

And refer to industry best practices here: https://docs.https.dev/acme-ops#use-one-name-per-certificate

Note that using multiple names per certificate does not fix the rate limit problems as scale grows, it only delays them.

**Comment by MichaelMure** [comment]
Thanks for taking the time.
