### ISSUE TITLE
certmagic satrt https  show unsafe on webbrowser 

### ISSUE THREAD

**Issue by zzxap** [caddyserver/certmagic#85]
import (
	"fmt"
	"net/http"
	"github.com/caddyserver/certmagic"
	"github.com/gorilla/mux"

)

func main() {
	serv := mux.NewRouter()
	serv.HandleFunc("/hi", hiTask)
	// read and agree to your CA's legal documents
	certmagic.DefaultACME.Agreed = true
	// provide an email address
	certmagic.DefaultACME.Email = "myemail"
	// use the staging endpoint while we're developing
	certmagic.DefaultACME.CA = certmagic.LetsEncryptStagingCA
	fmt.Println("start https server")
	err := certmagic.HTTPS([]string{"ssxx.com"}, serv)

	if err != nil {
		fmt.Println(err.Error())
	}
}

func hiTask(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("hi https"))
}

show unsafe on webbrowser   
rea alert

**Comment by mholt** [comment]
Let's Encrypt staging certificates are just test certificates and aren't trusted by any root programs.
