### ISSUE TITLE
Why there is no example of a graceful shutdown?

### ISSUE THREAD

**Issue by web3coach** [caddyserver/certmagic#93]
## What is your question?
I would like to know how to gracefully shutdown an HTTP server powered by CertMagic.

## What have you already tried?
I was able to implement it using this example commit code from 2018 https://github.com/gorilla/mux/pull/448/commits/f3d0b483bebe6af3f85a88c196a7b7ce208ccd0f, but it doesn't seems to be up-to-date and I have doubts given such a common use-case should be documented, or maybe it already happens behind the scenes somehow? Using context?

I also have seen [this question](https://github.com/caddyserver/certmagic/issues/10) on the graceful shutdown topic but the answer is also from 2018.

It would be great if the main `func HTTPS(domainNames []string, mux http.Handler) error {` would take a context parameter.

**Is there an official example how to gracefully handle shutdown?**

Thanks

**Comment by mholt** [comment]
I'm not sure this is relevant to CertMagic. If you need a graceful shutdown, just use https://golang.org/pkg/net/http/#Server.Shutdown. (If the `HTTPS()` function does not give you enough control, then use `TLS()` or `Listen()` or any other function that gives you the control you need.)
