### ISSUE TITLE
New tag/release with DNS01Solver support

### ISSUE THREAD

**Issue by delthas** [caddyserver/certmagic#94]
Hi,

There has been no certmagic release (/Git tag) for a while. The README mentions how to use the new DNS implementation, by setting `ACMEManager.DNS01Solver`, but the last tag was published before that, and we have to `go get` from `master` to use it.

Is there any chance you could push a new tag/release when you have time?

**Comment by mholt** [comment]
Coming soon, trying to work through my backlog of about 70 notifications/issues.

**Comment by mholt** [comment]
v0.12.0 has been tagged a few weeks ago.
