### ISSUE TITLE
certmagic assumes HTTP

### ISSUE THREAD

**Issue by emersion** [caddyserver/certmagic#97]
certmagic assumes that the server will use/support HTTP 1.1 and HTTP 2:

https://github.com/caddyserver/certmagic/blob/c6afa6e7a22e4b3035cc7b86377f83a421f0c3af/config.go#L682

This is incorrect e.g. if the server only supports HTTP 1.1 or if it's not an HTTP server.

**Comment by mholt** [comment]
Good point; in that case I recommend modifying NextProtos to remove the unsupported protocols. As far as I can tell, _most_ users of this library are using an HTTP server, and Go's HTTP server supports HTTP/2, so this seems like the right default.

**Comment by emersion** [comment]
How about adding h2 and http/1.1 only to the HTTP-specific helpers?

**Comment by mholt** [comment]
Good idea; on second look, [the godoc says](https://pkg.go.dev/github.com/caddyserver/certmagic?tab=doc#Listen) things like "and does not presume HTTP is also being served" so we can probably honor that better, and only add those two protocols in the `HTTPS()` function.

Fixed in #97

**Comment by emersion** [comment]
Thanks :heart:
